#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                                                             #
# Location: Made With LOVE IN ISRAEL !                        #
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
#                                                             #
###############################################################

AllHacKingTools(){
  echo "
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 01 ] >> Information Gathering:  -  Collects information from database
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 02 ] >> Exploitation Tools:  -  selection of tools for operation and hacking
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 03 ] >> Sniffing and Spoofing:  -  Tools for forgery of data and databases
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 04 ] >> Web Attack Tools:  -  Tools for hacking websites and servers
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 05 ] >> Cam Hacking Tools:  -  Tools for hacking cams and front camera
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 06 ] >> Remote Trojan RAT:  -  Utilities for creating RAT virus
        ${BYellow}${faintT}| ⁣⁣  ⁣⁣  ⁣    ⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣    ⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣    ⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣    ⁣
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 07 ] >> SQL injection-Tool:  -  Tools for creating viruses
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 08 ] >> SocialMedia Hacking:  -  Tools for hacking social networks
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 09 ] >> SMS spaming Tools:  -  Utilities for spam and anonymous SMS
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 10 ] >> Vulnerability Analysis:  -  Systems for vulnerability analysis
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 11 ] >> DarkSearch Tool:  -  Tools for Secret and Onion search
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 12 ] >> Phishing And IpHack:  -  Tools for phishing and fake websites
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 13 ] >> Passworld Attack:  -  Utilities for cracking passwords
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 14 ] >> Wordlist Generator:  -  Tools for Genering Worldlist
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 15 ] >> XSS Attack Tools:  -  Utilities for Attacking XSS
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 16 ] >> Discord leaks: - Discord mass users information
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 17 ] >> Telegram Info: - Mass Telegram users information
        ${BYellow}${faintT}|   ⁣    ⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣    ⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣    ⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣⁣  ⁣    ⁣  ⁣⁣  ⁣⁣
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 18 ] >> Other tools: -  Separate and other tools for hacking
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 19 ] >> Terminal Panel:  -  Termux control and special features
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 20 ] >> System Settings:  -  AllHackingTools control and special features
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 21 ] >> System License:  -  View the license in AllHackingTools
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 22 ] >> Update System:  -  Update system and all tools & menu and more utilitys
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 23 ] >> About System:  -  View system information and developer
        ${BYellow}${faintT}|──╼  ${resetT}${BRed}[${BYellow} 24 ] >> Exit System:  -  Log out of the AllHackingTools system '|lolcat -p 4.0
    "

}
