#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Author ]-╼▰ [ Leon Yaakobov ]-╼▰ [ AnLoMinus ]         #
#--╼▰[ Script Name ]-╼▰[ HacKingPro ]                         #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Update ]-╼▰[ 30-10-2022 ]                              #
#--╼▰[ Created ]-╼▰[ 2022 ]                                   #
#--╼▰[ Version ]-╼▰[ 1.8.0 ]                                  #
###############################################################
#-Operating System--------------------------------------------#
#--╼▰[ Kali ]-╼▰ [ ⌛️ ]                                       #
#--╼▰[ MacOS ]-╼▰ [ ✅ ]                                      #
#--╼▰[ Parrot ]-╼▰ [ ⌛️ ]                                     #
#--╼▰[ Pentoo ]-╼▰ [ ⌛️ ]                                     #
#--╼▰[ Windows ]-╼▰ [ ⌛️ ]                                    #
#--╼▰[ Predator ]-╼▰ [ ⌛️ ]                                   #
#-ToDO--------------------------------------------------------#
#  ┏━┳━┓
# ╾┃ 1 ┃╼ [Menu] - Offensive Protecting [Red-Menu]
# ╾┃ 2 ┃╼ [Menu] - Defensive Protecting [Blue-Menu]
# ╾┗━┻━┛╼
#
# The Hacking Methodology - contains the following progressive steps:
# 1. Information Gathering
# 2. Penetration
# 3. Optional: Guaranteeing Future Easier Access
# 4. Internal Reconnaissance
# 5. Optional: Movement
# 6. Intended Action Execution
# 7. Optional: Covering Tracks
#
###############################################
#------╼╼▰[ Granting Permissons ]-╼▰[ HacKingPro ]-╼▰[  ]
clear
chmod 777 HacKingPro
cp "$0" ~/HacKingPro
chmod a=rwx ~/HacKingPro
chmod a=rwx HacKingPro-Parts/Menu/*/*
# chmod a=rwx HacKingPro-Parts/Plugins/*
###############################################
#------╼╼▰[ Import ]-╼▰[ Parts ]-╼▰[ Main ]
# . HacKingPro-Parts/
#------╼╼▰[ Import ]-╼▰[ Parts ]-╼▰[ Plugins ]
. HacKingPro-Parts/Main/HacKingPro-Colors
. HacKingPro-Parts/Main/HacKingPro-Directories
. HacKingPro-Parts/Main/HacKingPro-Awesomes
. HacKingPro-Parts/Main/HacKingPro-ChecKing
. HacKingPro-Parts/Main/HacKingPro-Planning
. HacKingPro-Parts/Main/HacKingPro-Reports
. HacKingPro-Parts/Main/HacKingPro-NetWorKing
. HacKingPro-Parts/Main/HacKingPro-Status
# . Menu/AnLoMinus/AnLoMinus-KoTH-Pro
HacKingPro=$(echo "${BRed}Hac${BYellow}King${BBlue}Pro$resetT")
#------╼╼▰[ Import ]-╼▰[ Parts ]-╼▰[ Menu ]
. HacKingPro-Parts/Menu/00/HacKingPro-00
. HacKingPro-Parts/Menu/01/HacKingPro-01
. HacKingPro-Parts/Menu/02/HacKingPro-02
# . HacKingPro-Parts/Menu/03/HacKingPro-03
# . HacKingPro-Parts/Menu/04/HacKingPro-04
# . HacKingPro-Parts/Menu/05/HacKingPro-05
# . HacKingPro-Parts/Menu/06/HacKingPro-06
# . HacKingPro-Parts/Menu/07/HacKingPro-07

##########################################################
#╾┣━╋━━-╼▰[ About ]--╼▰ [ AnLoMinus ]--╼▰ [ HacKingPro ] #
##########################################################

###################################
#------╼╼▰[ Variables ]-╼▰[ Head] #
###################################
#--╼▰[ Variable ]-╼▰ [ Set Parameters ]
g1="${1}" # Parameter -> Name
g2="${2}" # Parameter -> IP
g3="${3}" # Parameter -> DNS | if DNS exist, i try resolve his IP and Automatic set it as a TargetIP
g4="${4}" # Parameter -> Email
g5="${5}" # Parameter -> Phone
##################################
#------╼╼▰[ Variables ]-╼▰[ End] #
##################################
targetNAME="${g1}"
targetIP="${g2}"
targetDns="${g3}"
targetEmail="${g4}"
targetPhone="${g5}"

#--╼[ ChecKing ]--╼▰ [ If ]--╼▰ [ Parameters is = 0 ]
if [ "$#" -eq 0 ]; then
  echo " "
  MiniHeaderSta "${LRed} ❌ you did not pass any parameter ❌"
  echo "${ORANGE}    |─${resetT}${BYellow}╼▰ My name is ${BGreen}${HacKingPro}${resetT}"
  echo "${ORANGE}    |─${resetT}${BYellow}╼▰ I was called with ${BGreen}$#${resetT}${ORANGE} Parameters"
  MiniHeaderEnd "${LRed} ❌ you did not pass any parameter ❌"
fi
#--╼[ ChecKing ]--╼▰ [ If ]--╼▰ [ Parameters is not = 0 ]
# if [ "$#" -ne 0 ]; then
#   #--╼[ ChecKing ]--╼▰ [ 01 ]--╼▰ [ Name Parameters ]
#   if [ -z ${g1}  ]; then
#     # IF NO TARGET SET AnLoMinus
#     if [ -z "$targetNAME" ]; then
#       # setting target name
#       targetNAME="AnLoMinus"
#     fi
#   else
#     # setting target name
#     targetNAME="${g1}"
#   fi
#   #--╼[ ChecKing ]--╼▰ [ 02 ]--╼▰ [ IP Parameters ]
#   if [ -z ${g2}  ]; then
#     # IF NO TARGET SET AnLoMinus
#     if [ -z "$targetIP" ]; then
#       # setting target name
#       targetIP=""
#     fi
#   else
#     # setting target name
#     targetIP="${g2}"
#   fi
#   #--╼[ ChecKing ]--╼▰ [ 03 ]--╼▰ [ Dns Parameters ]
#   if [ -z ${g3}  ]; then
#     if [ ! -z "$targetDns" ]; then
#       #statements
#       GetIP="$(ping -c 1 "${targetDns}" | grep ttl | cut -d " " -f4 |  tr  -d :)"
#       targetIP="${GetIP}"
#     else
#       targetDns="xXx.AnLoMinus.xXx"
#     fi
#     if [ -z "$targetDns" ]; then
#       # setting target name
#       targetDns=""
#     fi
#     if [ ! -z ${targetDns} ]; then
#       #statements
#       GetIP="$(ping -c 1 "${targetDns}" | grep ttl | cut -d " " -f4 |  tr  -d :)"
#       targetIP="${GetIP}"
#     fi
#   else
#     # setting target name
#     targetDns="${g3}"
#     GetIP="$(ping -c 1 "${targetDns}" | grep ttl | cut -d " " -f4 |  tr  -d :)"
#     targetIP="${GetIP}"
#   fi
#   #--╼[ ChecKing ]--╼▰ [ 04 ]--╼▰ [ Email Parameters ]
#   if [ -z ${g4}  ]; then
#     # IF NO TARGET SET AnLoMinus
#     if [ -z "$targetEmail" ]; then
#       # setting target name
#       targetEmail=""
#     fi
#   else
#     # setting target name
#     targetEmail="${g4}"
#   fi
#   #--╼[ ChecKing ]--╼▰ [ 05 ]--╼▰ [ Phone Parameters ]
#   if [ -z ${g5}  ]; then
#     # IF NO TARGET SET AnLoMinus
#     if [ -z "$targetPhone" ]; then
#       # setting target name
#       targetPhone=""
#     fi
#   else
#     # setting target name
#     targetPhone="${g5}"
#   fi
#   ReportPlanning
# fi
MainDirectories

######################################
#------╼╼▰[ Variables ]--╼▰ [ Head ] #
######################################
#--╼▰ [ About ]
LastUPDATE(){
  echo "30 October 2022"
}
ToolSource(){
  echo "https://github.com/AnLoMinus/HacKingPro"
}
AnLoMinus(){
  echo "${BGreen}An${DGrey}Lo${BRed}Minus"
}
MyVersion(){
  echo "${DGrey}V1.8.0" # 30-10-2022
}
#╼╼▰[ Variables ]--╼▰ [ User Interface ]
Press_ENTER(){
  printf "\n\n${BYellow}                🔶    Press ENTER    🔶     ${BGreen}\n\n"
  read cmd
}
Press_Enter_To_START=$(echo "\n\n${BYellow}                🔶    Press Enter To START    🔶     ${BGreen}\n\n")
InvalidOption=$(echo "\n\t\t ${BGreen}»»» ${HacKingPro} ${LRed}Invalid Option ${BRed}¯\_(ツ)_/¯ \n")
#╼╼▰[ Variables ]--╼▰ [ Date ]
year=$(date +%Y)
month=$(date +%m)
day=$(date +%d)
hour=$(date +%H)
minute=$(date +%M)
second=$(date +%S)
DMY=$(date +%d-%m-%y)
CurrentDate=$(echo "${DGrey}$day-$month-$year")
StartingTime=$(echo "${DGrey}$hour:$minute:$second")
#╼╼▰[ HacKingPro ]--╼▰ [ Logo ]--╼▰  [ Variables ]
HacKingProLogo(){
  echo "${BBlue}
${BRed}     █████   █████                    ${BYellow}█████   ████  ███                      ${BBlue}███████████
${BRed}    ░░███   ░░███                    ${BYellow}░░███   ███░  ░░░   $(MyVersion)           ${BBlue}░░███░░░░░███ $(AnLoMinus)
${BRed}     ░███    ░███   ██████    ██████  ${BYellow}░███  ███    ████  ████████    ███████ ${BBlue}░███    ░███ ████████   ██████
${BRed}     ░███████████  ░░░░░███  ███░░███ ${BYellow}░███████    ░░███ ░░███░░███  ███░░███ ${BBlue}░██████████ ░░███░░███ ███░░███
${BRed}     ░███░░░░░███   ███████ ░███ ░░░  ${BYellow}░███░░███    ░███  ░███ ░███ ░███ ░███ ${BBlue}░███░░░░░░   ░███ ░░░ ░███ ░███
${BRed}     ░███    ░███  ███░░███ ░███  ███ ${BYellow}░███ ░░███   ░███  ░███ ░███ ░███ ░███ ${BBlue}░███         ░███     ░███ ░███
${BRed}     █████   █████░░████████░░██████  ${BYellow}█████ ░░████ █████ ████ █████░░███████ ${BBlue}█████        █████    ░░██████
${BRed}    ░░░░░   ░░░░░  ░░░░░░░░  ░░░░░░  ${BYellow}░░░░░   ░░░░ ░░░░░ ░░░░ ░░░░░  ░░░░░███${BBlue}░░░░░        ░░░░░      ░░░░░░
${BYellow}                                                                    ███ ░███
${BYellow}                                                                   ░░██████
${BYellow}                                                                    ░░░░░░                              "
}
#╼╼▰[ HacKingPro ]--╼▰ [ lahs ]--╼▰ [ ls -lahs ]
lahs(){
  AwesomeAsking "[ ls | nano ] ?"
  AwesomeLine "Listing Fils in Curret Directory"
  ls -lahs "$1"
  AwesomeLine "Listing Fils in Curret Directory"
  read -p "$ls_lahs"
}
#####################################
#------╼╼▰[ Variables ]--╼▰ [ End ] #
#####################################
xDirectories
#-╼▰[ HacKingPro ]-╼▰▰[ Status ]-╼▰▰  [ Header ]
ToolHeaderRun(){
  ToolHeader=$(echo "
    ${BGreen}${faintT}┌──╼ ${resetT}${BRed}[${BCyan}${faintT} Version${resetT} ${BRed}]${BGreen}${faintT}──────${resetT}${BGreen}▰${resetT} ${BRed}[${BCyan} $(MyVersion) ${BRed}]
    ${BGreen}${faintT}|──╼ ${resetT}${BRed}[${BCyan}${faintT} Aouther${resetT} ${BRed}]${BGreen}${faintT}──────${resetT}${BGreen}▰${resetT} ${BRed}[${BCyan} $(AnLoMinus) ${BRed}]
    ${BGreen}${faintT}|──╼ ${resetT}${BRed}[${BCyan}${faintT} Tool Name${resetT} ${BRed}]${BGreen}${faintT}────${resetT}${BGreen}▰${resetT} ${BRed}[${BCyan} $boldT$slowBlink${HacKingPro}$resetT ${BRed}]
    ${BGreen}${faintT}|──╼ ${resetT}${BRed}[${BCyan}${faintT} Last Update${resetT} ${BRed}]${BGreen}${faintT}──${resetT}${BGreen}▰${resetT} ${BRed}[${BCyan} $(LastUPDATE) ${BRed}]
    ${BGreen}${faintT}|──╼ ${resetT}${BRed}[${BCyan}${faintT} Current PID${resetT} ${BRed}]${BGreen}${faintT}──${resetT}${BGreen}▰${resetT} ${BRed}[${BCyan} $(echo "$$") ${BRed}]
    ${BGreen}${faintT}└──╼ ${resetT}${BRed}[${BCyan}${faintT} Source${resetT} ${BRed}]${BGreen}${faintT}───────${resetT}${BGreen}▰${resetT} ${BRed}[${DGrey} $(ToolSource) ${BRed}]")
  echo "$ToolHeader"
}
#-╼▰[ HacKingPro ]-╼▰▰ [ Status ]-╼▰▰ [ Target ]-╼▰▰
TargetStatus(){
  echo "
    ${ORANGE}${faintT}┌──╼${resetT}${BBlue}┤${ORANGE} Target Status ${BBlue}├${ORANGE}${faintT}───────╼${resetT}${BCyan}▰▰▰
    ${ORANGE}${faintT}│
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetIP)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}IP${BBlue}: ${BGreen}${targetIP}
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetDns)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Dns${BBlue}: ${BGreen}${targetDns}
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetName)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Name${BBlue}: ${BGreen}${targetNAME}
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetEmail)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Email${BBlue}: ${BGreen}${targetEmail}
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetPhone)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Phone${BBlue}: ${BGreen}${targetPhone}
    ${ORANGE}${faintT}│
    ${ORANGE}${faintT}└───────────────────────────────╼${resetT}${BCyan}▰▰▰
"
}
#-╼▰[ HacKingPro ]-╼▰▰ [ Status ]-╼▰▰ [ Target ]-╼▰▰ ╼▰▰ [ Running ]
TargetStatusRun(){
  ToolStatus=$(echo "
    ${InternetStatus}
    ${BCyan}${faintT}┌──${resetT}${BRed}[${BCyan} ${slowBlink}P${resetT} ${BRed}]${faintT}${BCyan}──${resetT}${BCyan}╼▰ ${BRed}[${faintT}${BCyan} ⚡️ Planning and Scoping 🎯 ${BRed}]${BCyan}${faintT}───────╼${resetT}${BCyan}▰▰▰
    ${BCyan}${faintT}|
    ${BCyan}${faintT}|──${resetT}${BRed}[${DGrey} Full Time ${BRed}]${faintT}${BCyan}──╼${resetT} ${BRed}[${DGrey} $(date) ${BRed}]
    ${BCyan}${faintT}|──${resetT}${BRed}[${DGrey} Current Date ${BRed}]${faintT}${BCyan}──╼${resetT} ${BRed}[${DGrey} ${CurrentDate} ${BRed}]
    ${BCyan}${faintT}|──${resetT}${BRed}[${DGrey} Starting Time ${BRed}]${faintT}${BCyan}──╼${resetT} ${BRed}[${DGrey} ${StartingTime} ${BRed}]
    ${BCyan}${faintT}|
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetIP)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} IP ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetIP} ${DGrey}]
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetDns)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} Dns ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetDns} ${DGrey}]
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetName)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} Name ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetNAME} ${DGrey}]
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetEmail)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} Email ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetEmail} ${DGrey}]
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetPhone)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} Phone ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetPhone} ${DGrey}]
    ${BCyan}${faintT}|
    ${BCyan}${faintT}└──${resetT}${BRed}[${BCyan} CL ${BRed}]${faintT}${BCyan}──${resetT}${BCyan}╼▰ ${BRed}[${faintT}${BCyan} 🧹 Cleaning Target Variables  🧹 ${BRed}]${BCyan}${faintT}───────╼${resetT}${BCyan}▰▰▰
    ")
    echo "$ToolStatus"
}

about() {
  clear
  # HacKingProLogo1
  echo "${BBlue}
                              .
                          ..',,'..
                        .',,,,,,,,,.
                       .',,,'..',,,,'.
                      .',,'.     .,,,'
                     .',,.        .,,,.
                    .',..           .,,.
                    .'.              ..,.
                    .                  .'
                   ..   ${ORANGE}  Aภl๏miภuຮ    .
                   ..                   .
                   ..                  ...
            ....''''.    ${HacKingPro}${BGreen}    .','''....
          .',,,,,,,,'..               ..',,,,,,,,'.
         ...'',,,,,,,'...          ....',,,,,,,,'...
        ....'',;;;;;;;,,'''......'''',,;;;;;;;,'''...
       ......'',,;;;:::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/:'.
       .....'.'',,;;::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/'....
       .......',,;;::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/,......
       .'''''',,;;::/xxxxxxxxxx${BCyan}DAT0S${BGreen}xxxxxxxxxxxx/,.......
      ..'''',',;;::/xxxxxxxxx${BBlue}4NL0M1NU2${BGreen}xxxxxxxxx/,'''''...
     ........';;::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/:'.........
    ......  .':::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/::'..  ......
    ......:.;:::/xxxxxxxxxxxxxxxxxxxxxxxxxxx/::;'c,':......
     .''..cc.''''''',,,,,,,;;;;;,,,,,,,,''''....:.cc..''."

         AwesomeLine "Welcome to ${HacKingPro}"
         ToolHeaderRun
         AwesomeLine "Welcome to ${HacKingPro}"

  echo "
    ${DGrey}┏──⇢ ${BRed}[${LRed} ${HacKingPro} ${Color_Off}is a Penetration Testing Tool ❕❕❕ ${BRed}]
    ${DGrey}┣──⇢ ${BRed}[${LRed} ${HacKingPro} ${Color_Off}Written by ${BCyan}Leon Yaakobov ${Color_Off}For Showing Skills ${BRed}]
    ${DGrey}┗──⇢ ${BRed}[${LRed} ${HacKingPro} ${Color_Off}Tool for ${BRed}Red Teams ${BBlue} Blue Teams ${BRed}]

    ${DGrey}┏==⥤ ${Color_Off}[${LRed} ❌ ❗ ☣️ Warning ☣️ ❗ ❌ ${Color_Off}]
    ${DGrey}|
    ${DGrey}┣==⥤ ${Color_Off}[${LRed} ❗ I’m not responsible for any misuse or damage caused by this program.❗ ${Color_Off}]
    ${DGrey}|
    ${DGrey}┗==⥤ ${Color_Off}[${LRed} ❗ Use this tool at your own ${BRed}Risk ❗${Color_Off}]

    ${DGrey}┌──${BRed}[${DGrey} AnyTool ${BRed}]${BYellow}╼▰  ${BRed}[${DGrey} Many Systems HacKing Tools Downloader ${HacKingPro} ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} About ${BRed}]${BYellow}╼▰  ${BRed}[${DGrey} Information About The ${HacKingPro} Tool ${BRed}]"

   # Press_ENTER

   if [[ $SystemArchitecture == "darwin-amd64" ]]; then
     #statements
     open -u http://github.com/AnLoMinus/HacKingPro
   fi

}

if [[ $1 == "help" ]]; then
  #statements
  echo " Help Center"
  about
  read; exit;
fi
######################################
#------╼╼▰[ Main Menu ]--╼▰ [ Head ] #
######################################
#-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0#
#-0-------START Checking---------0-#
#-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0#
ReportPlanning
clear
Check_System
AwesomeWarning
AwesomeAskingWarning "Want start anyway?"
clear
AwesomeLine "Welcome to ${HacKingPro}"
ToolHeaderRun
if [ "$#" -eq 0 ]; then
  echo " "
  MiniHeaderSta "${LRed} ❌ you did not pass any parameter ❌"
  echo "${ORANGE}    |─${resetT}${BYellow}╼▰ My name is ${BGreen}${HacKingPro}${resetT}"
  echo "${ORANGE}    |─${resetT}${BYellow}╼▰ I was called with ${BGreen}$#${resetT}${ORANGE} parameters"
  MiniHeaderEnd "${LRed} ❌ you did not pass any parameter ❌"
else
  AwesomeParameters
fi
AwesomeLine "Welcome to ${HacKingPro}"

Press_ENTER
#-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-#
#-0-------END Checking--------0-#
#-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-#

HackTypePro(){
  while true; do
    clear
    ToolHeaderRun
    TargetStatusRun
    echo "
    [ BB ]--[ Black Box ] - Done without any knowledge of the system or network.
    [ WB ]--[ White Box ] - When the attacker have complete knowledge of the system provided by the owner/target.
    [ GB ]--[ Gray Box ] - When the attacker has some knowledge of the system and/or network "
    case $cmd in
    "bb" | "BB" | "Black Box" ) clear ;;
    "wb" | "WB" | "White Box" ) clear ;;
    "gb" | "GB" | "Gray Box" ) clear ;;
    esac
  done
}
#--╼[ Main Menu ]
MainMenu(){
  while true; do
    clear
    MainDirectories
    cd "${MainDirectoriy}"
    ToolHeaderRun
    TargetStatusRun
    HacKingProMenuMain=$(echo "${BRed}
    ${BYellow}${faintT}┌──${resetT}${BRed}[${BYellow} ${HacKingPro} ${BRed}]${BYellow}${faintT}───────╼${resetT}${BYellow}▰▰▰
    ${BYellow}${faintT}|
    ${BYellow}${faintT}|──┲─${resetT}${BYellow}╼▰ ${resetT}${BRed}[${BYellow} 0 ${BRed}]${BYellow}${faintT}──${resetT}${BYellow}╼▰ ${resetT}${BRed}[${BYellow} Anonymity ${BRed}]
    ${BYellow}${faintT}|  ┖──────────╼ ${BRed}[${BYellow} Anonymity ${BRed}]
    ${BYellow}${faintT}|
    ${BYellow}${faintT}|──┲─${resetT}${BYellow}╼▰ ${resetT}${BRed}[${BYellow} 1 ${BRed}]${BYellow}${faintT}──${resetT}${BYellow}╼▰ ${resetT}${BRed}[${BYellow} Reconnaissance & Information Gathering ${BRed}]
    ${BYellow}${faintT}|  ┖──────────╼ ${BRed}[${BYellow} Get Information about the Target Organization ${BRed}]
    ${DGrey}${faintT}|
    ${DGrey}${faintT}|──┲─${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} 2 ${BRed}]${BYellow}${faintT}──${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} Weaponization ${BRed}]
    ${DGrey}${faintT}|  ┖──────────╼ ${BRed}[${DGrey} Create Malicious Program or Exploits ${BRed}]
    ${DGrey}${faintT}|
    ${DGrey}${faintT}|──┲─${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} 3 ${BRed}]${BYellow}${faintT}──${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} Delivery ${BRed}]
    ${DGrey}${faintT}|  ┖──────────╼ ${BRed}[${DGrey} Send Weaponized Program to Target ${BRed}]
    ${DGrey}${faintT}|
    ${DGrey}${faintT}|──┲─${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} 4 ${BRed}]${BYellow}${faintT}──${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} Exploitation ${BRed}]
    ${DGrey}${faintT}|  ┖──────────╼ ${BRed}[${DGrey} Start Weaponized Program Attacks the Target ${BRed}]
    ${DGrey}${faintT}|
    ${DGrey}${faintT}|──┲─${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} 5 ${BRed}]${BYellow}${faintT}──${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} Installation ${BRed}]
    ${DGrey}${faintT}|  ┖──────────╼ ${BRed}[${DGrey} Install Malware on the Target System, Which Allows Control Remotely ${BRed}]
    ${DGrey}${faintT}|
    ${DGrey}${faintT}|──┲─${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} 6 ${BRed}]${BYellow}${faintT}──${resetT}${BYellow}╼▰ ${resetT}${BRed}[${DGrey} Command and Control ${BRed}]
    ${DGrey}${faintT}|  ┖──────────╼ ${BRed}[${DGrey} Use Malware to take control of Target System ${BRed}]
    ${BYellow}${faintT}|
    ${BYellow}${faintT}|──┲─${resetT}${BYellow}╼▰ ${resetT}${BRed}[${BYellow} 7 ${BRed}]${BYellow}${faintT}──${resetT}${BYellow}╼▰ ${resetT}${BRed}[${BYellow} Actions on Objective ${BRed}]
    ${BYellow}${faintT}|  ┖──────────╼ ${BRed}[${BYellow} Destruction ${BRed}]
    ${BYellow}${faintT}|
    ${BYellow}${faintT}└──${resetT}${BRed}[${DGrey} X ${BRed}]${BYellow}${faintT}──╼ ${resetT}${BRed}[${DGrey} Exit / Quit / Close ${BRed}]

    ${BGreen}┌──${BRed}[${ORANGE} Arsenal ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BGreen} $ArsenalCommand ${BRed}]${BGreen}${resetT}
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} 🔮 ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BGreen}   ")
    read -p "$HacKingProMenuMain" cmd
    case $cmd in
      qqqq )
      HKP_HTML_Export
      read -p "done ! "
      open ${targetNAME}_HKP_REPORT.html
      ;;
      lpi|lpic|Linux+ ) . HacKingPro-Parts/Linux/LinuxPlusPro ; _LinuxPlusProMenu;;
      KoTHPro)
      AnLoMinus_Main_Menu
      ;;
      report )
      ReportPlanning
      ;;
      "?"|help|about|About )
      about
      Press_ENTER
      ;;
      00|0 )
      Anonymity(){
        while true; do
          clear
          ToolHeaderRun
          TargetStatusRun
          HacKingProMenuMain=$(echo "${BRed}
    ${DGrey}[0]───${resetT}${BYellow}╼▰ ${BRed}[${DGrey} Anonimity ${BRed}]

    ${DGrey}┌──${BRed}[${LGreen} NetWorKing ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${BGreen}${slowBlink} NetPro ${resetT}${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BGreen} NetWorKingPro ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BGreen}${faintT} NetWorKing Controller ${resetT}${BRed}]

    ${DGrey}┌──${BRed}[${BWhite} 00 ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BWhite} Installer ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BWhite} Installing Anonymous Tools ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${BWhite} 01 ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BWhite} Cover Me ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BWhite} Clean Logs & History${BRed}]

    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BGreen}───${resetT}${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BGreen}───${resetT}${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Anonymity ${BRed}]${BYellow}╼▰  ${BGreen}   ")
          read -p "$HacKingProMenuMain" cmd
          case $cmd in
            p|P )
            HacKingProPlanning
            ReportPlanning
            ;;
            ls )
            lahs
            ;;
            0|00 )
            clear
            echo ${faintT}
            AnonymousInstaller
            Press_ENTER
            ;;
            1|01 )
            clear
            CoverMe
            Press_ENTER
            ;;
            nt|NT|netpro|NetPro)
            Info_LocalNet
            while true; do
              clear
              ToolHeaderRun
              TargetStatusRun
              #statements
              NetWorKingPro
            done
            ;;
            x|X|exit|EXIT )
            cd ${MainDirectoriy}
            clear
            AwesomeLineExit
            break
            ;;
        esac
      done
      }
      Anonymity
      ;;
      01|1 )
      # Page Header
      while true; do
        #statements
        clear
        # cd "$x_Menu_1"
        ToolHeaderRun
        TargetStatusRun
        HacKingProMenuMain=$(echo "${BRed}
    ${DGrey}┌──┲────╼ ${BRed}[${BYellow} Reconnaissance & Information Gathering ${BRed}]
    ${DGrey}|  ┖─┲──╼ ${BRed}[${BYellow} Intruder picks a target, researches it, and looks for vulnerabilities ${BRed}]
    ${DGrey}|    ┖──╼ ${BRed}[${BYellow} Intruder selects target, researches it, and attempts to identify vulnerabilities in the target network. ${BRed}]
    ${DGrey}|
    ${DGrey}| ┏───╼▰ ${BRed}[${BYellow} CPI ${BRed}]${BGreen}╼╼▰▰ ${BRed}[${BYellow} Collecting Public Information ${BRed}]
    ${DGrey}| ┣───╼▰ ${BRed}[${BYellow} CMI ${BRed}]${BGreen}╼╼▰▰ ${BRed}[${BYellow} Collecting Machine Information ${BRed}]
    ${DGrey}| ┣───╼▰ ${BRed}[${BYellow} CNI ${BRed}]${BGreen}╼╼▰▰ ${BRed}[${BYellow} Collecting Network Information ${BRed}]
    ${DGrey}| ┣───╼▰ ${BRed}[${BYellow} CSI ${BRed}]${BGreen}╼╼▰▰ ${BRed}[${BYellow} Collecting Social Information ${BRed}]
    ${DGrey}| ┖───╼▰ ${BRed}[${BYellow} CLI ${BRed}]${BGreen}╼╼▰▰ ${BRed}[${BYellow} Collecting Local Information ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} X ${BRed}] 🤴 Exit / Quit / Close

    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Reconnaissance & Information Gathering ${BRed}]${BYellow}╼▰  ${BGreen}   ")
          read -p "$HacKingProMenuMain" cmd
          case $cmd in
            ls )
            lahs
            ;;
            p|P )
            HacKingProPlanning
            ;;
            # Collecting Public Information
            cpi|CPI )
            Checking_IP_Target
            Recon_Start
            while true; do
              cd "${x_Menu_1_CPI}"
              cd "${MainDirectoriyCaseNameRecon}"
              clear
              ToolHeaderRun
              TargetStatusRun
              HacKingProMenuMain=$(echo "${BRed}
              ${DGrey}  ┌─${BRed}[${BYellow} CPI ${BRed}]${BGreen}──╼▰  ${BRed}[${BYellow} Collecting Public Information ${BRed}]
              ${DGrey}  ┖─┲──${BRed}[${DGrey} p0 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} Ping Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} p1 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} Arp Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} p2 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} Nslookup Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} p3 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} Dig Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} p4 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} WhoIs Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} p5 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} Dirb Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} p6 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} TraceRoute Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} p7 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} Nmap Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} p8 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} IpInfo Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} p9 ${BRed}]${BYellow}╼╼▰  ${BRed}[${DGrey} Robots.txt Scan ${BRed}]
              ${DGrey}    |──${BRed}[${DGrey} all ${BRed}]${BYellow}╼▰  ${BRed}[${DGrey} All Scans ${BRed}]
              ${DGrey}    ┖──${BRed}[${DGrey} show ${BRed}]${BYellow}╼▰  ${BRed}[${DGrey} show Scan ${BRed}]
              ${DGrey}
              ${DGrey}└──${BRed}[${DGrey} X ${BRed}] 🤴 Exit / Quit / Close

              ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
              ${BGreen}|
              ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
              ${BGreen}|
              ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Information Gathering ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${slowBlink}CPI${resetT} ${BRed}]${BYellow}╼▰  ${BGreen}  ")
              read -p "$HacKingProMenuMain" cmd
              case $cmd in
                show )
                less ${targetNAME}-HacKingPro-Recon-Log.md
                ;;
                x|X|exit|quit|Exit )
                clear
                AwesomeLineExit
                break
                ;;
                ls )
                lahs
                ;;
                p0 )
                # Ping Scan Log
                infoPing
                ;;
                p1 )
                # Arp Scan Log
                infoArp
                ;;
                p2 )
                # Nslookup Scan Log
                infoNsLookUp
                ;;
                p3 )
                # Dig Scan Log
                infoDig
                ;;
                p4 )
                # WhoIs Scan Log
                infoWhois
                ;;
                p5 )
                # Dirb Scan Log
                infoDirb
                ;;
                p6 )
                # TraceRoute Scan Log
                infoTraceRoute
                ;;
                p7 )
                # Nmap Scan Log
                infoNmap
                ;;
                p8 )
                # IpInfo Scan Log
                infoIp
                ;;
                p9 )
                # Robot.txt Scan Log
                infoRobots
                ;;
                all|ALL|cpi|CPI )
                AllInfo
                less ${targetNAME}-HacKingPro-Recon-Log.md
                ;;
              esac
            done
            ;;
            # Collecting Domain Information
            cdi|CDI )
            # SubMaxPro
            SubDomFind ${targetIP} >> ${MainDirectoriyCaseNameRecon}-${targetNAME}-SubDomFind.log
            ;;
            # Collecting Network Information
            cni|CNI )
            while true; do
              cd "${x_Menu_1_CNI}"
              clear
              ToolHeaderRun
              TargetStatusRun
              HacKingProMenuMain=$(echo "${BRed}
    ${DGrey}┏${BRed}[${BYellow} CNI ${BRed}]${BGreen}── ${BRed}[${BYellow} Network Information ${BRed}]
    ${DGrey}┖─┲──${BRed}[${DGrey} n0 ${BRed}]${BYellow}╼▰  ${BRed}[${DGrey} Nmap Scan ${BRed}]
    ${DGrey}  ┖──${BRed}[${DGrey} ni ${BRed}]${BYellow}╼▰  ${BRed}[${DGrey} NetInfo Scan ${BRed}]

    ${DGrey}┌──${BRed}[${BYellow} Collecting Network Information ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} User Enumeration  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} System Groups  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} Network Hosts  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} OS Hostnames  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} OS System Type  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} System Banners  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} SSL Certificates  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} Open Ports and More  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} X ${BRed}] 🤴 Exit / Quit / Close

    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Information Gathering ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} CMI ${BRed}]${BYellow}╼▰  ${BGreen}  ")
                read -p "$HacKingProMenuMain" cmd
                case $cmd in
                  x|X|exit|quit|Exit )
                  clear
                  AwesomeLineExit
                  break
                  ;;
                  ls )
                  lahs
                  ;;
                esac
              done
            ;;
            # Collecting Machie Information
            cmi|CMI )
            while true; do
              cd "${x_Menu_1_CMI}"
              clear
              ToolHeaderRun
              TargetStatusRun
              HacKingProMenuMain=$(echo "${BRed}
    ${DGrey}┏${BRed}[${BYellow} CMI ${BRed}]${BGreen}── ${BRed}[${BYellow} Machine Information ${BRed}]
    ${DGrey}┖─┲──${BRed}[${DGrey} m0 ${BRed}]${BYellow}╼▰  ${BRed}[${DGrey} xxx Scan ${BRed}]
    ${DGrey}  ┖──${BRed}[${DGrey} m1 ${BRed}]${BYellow}╼▰  ${BRed}[${DGrey} xxx Scan ${BRed}]

    ${DGrey}┌──${BRed}[${BYellow} Collecting Machine Information ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${DGrey} 00 ${BRed}]${BGreen}── ${BRed}[${DGrey} HTML Full Report  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} User Enumeration  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} System Groups  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} Network Hosts  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} OS Hostnames  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} OS System Type  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} System Banners  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} SSL Certificates  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|──${BRed}[${DGrey} !! ${BRed}]${BGreen}── ${BRed}[${DGrey} Open Ports and More  ${BRed}]${BGreen}── ${BRed}[${DGrey} $XXX ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} X ${BRed}] 🤴 Exit / Quit / Close

    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Information Gathering ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} CMI ${BRed}]${BYellow}╼▰  ${BGreen}  ")
                read -p "$HacKingProMenuMain" cmd
                case $cmd in
                  0|00 )

                  clear
                  HKP_HTML_Export
                  echo '
                  <div class="row card-body gradient-border raise">
                    <h3 class="text-center glitch b2" hackbox-heading>' >> ${targetNAME}_HKP_REPORT.html
                    echo "HacKingPro | Linux Privilege Escalation Checklist" >> ${targetNAME}_HKP_REPORT.html
                    echo '
                    </h3>
                    <br>
                    <code>
                      ' >> ${targetNAME}_HKP_REPORT.html
                      # <div class="form-check">
                      #   <input class="form-check-input" type="checkbox" value="" id="defaultCheck2" checked="">
                      #   <label class="form-check-label" for="defaultCheck2"> Indeterminate </label>
                      # </div>
                      # <div class="form-check">
                      #   <input class="form-check-input" type="checkbox" value="" id="defaultCheck3" checked="">
                      #   <label class="form-check-label" for="defaultCheck3"> Checked </label>
                      # </div>
                      # <div class="form-check">
                      #   <input class="form-check-input" type="checkbox" value="" id="disabledCheck1" disabled="">
                      #   <label class="form-check-label" for="disabledCheck1"> Disabled Unchecked </label>
                      # </div>
                      # <div class="form-check">
                      #   <input class="form-check-input" type="checkbox" value="" id="disabledCheck2" disabled="" checked="">
                      #   <label class="form-check-label" for="disabledCheck2"> Disabled Checked </label>
                      # </div>

                      echo '
                      <div class="card-body">
                          <div class="row gy-3">
                            <div class="col-md">
                              <small class="text-light fw-semibold">Checkboxes</small>
                              <div class="form-check mt-3">
                                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                                <label class="form-check-label" for="defaultCheck1"> Unchecked </label>
                              </div>
                            </div>
                          </div>
                        </div>' >> ${targetNAME}_HKP_REPORT.html
                  echo '
                    </code>
                  </div>
                  <br>
                  ' >> ${targetNAME}_HKP_REPORT.html

                  HKP_PrivEsc_Checklist_HTML_Export_Template(){
                    echo "<h3 class="text-center glitch b2" hackbox-heading> $(date) </h3>" >> ${targetNAME}_HKP_REPORT.html
                    echo '
                    <div class="row card-body gradient-border raise">
                      <h3 class="text-center glitch b2" hackbox-heading>' >> ${targetNAME}_HKP_REPORT.html
                      echo "Linux Privilege Escalation | Checklist" >> ${targetNAME}_HKP_REPORT.html
                      echo '
                      </h3>
                      <br>
                      <code>
                        <pre>' >> ${targetNAME}_HKP_REPORT.html
                        echo "
                        Checklists
                        Kernel and distribution release details

                        # System Information:
                        Hostname

                        # Networking details:
                        Current IP
                        Default route details
                        DNS server information

                        # User Information:
                        Current user details
                        Last logged on users
                        Shows users logged onto the host
                        List all users including uid/gid information
                        List root accounts
                        Extracts password policies and hash storage method information
                        Checks umask value
                        Checks if password hashes are stored in /etc/passwd
                        Extract full details for 'default' uid's such as 0, 1000, 1001 etc
                        Attempt to read restricted files i.e. /etc/shadow
                        List current users history files (i.e .bash_history, .nano_history, .mysql_history , etc.)
                        Basic SSH checks

                        # Privileged access:
                        Which users have recently used sudo
                        Determine if /etc/sudoers is accessible
                        Determine if the current user has Sudo access without a password
                        Are known 'good' breakout binaries available via Sudo (i.e. nmap, vim etc.)
                        Is root's home directory accessible
                        List permissions for /home/

                        # Environmental:
                        Display current $PATH
                        Displays env information

                        # Jobs/Tasks:
                        List all cron jobs
                        Locate all world-writable cron jobs
                        Locate cron jobs owned by other users of the system
                        List the active and inactive systemd timers

                        # Services:
                        List network connections (TCP & UDP)
                        List running processes
                        Lookup and list process binaries and associated permissions
                        List inetd.conf/xined.conf contents and associated binary file permissions
                        List init.d binary permissions
                        Version Information (of the following):
                        Sudo
                        MYSQL
                        Postgres
                        Apache
                        Checks user config
                        Shows enabled modules
                        Checks for htpasswd files
                        View www directories
                        Default/Weak Credentials:
                        Checks for default/weak Postgres accounts
                        Checks for default/weak MYSQL accounts

                        # Searches:
                        Locate all SUID/GUID files
                        Locate all world-writable SUID/GUID files
                        Locate all SUID/GUID files owned by root
                        Locate 'interesting' SUID/GUID files (i.e. nmap, vim etc)
                        Locate files with POSIX capabilities
                        List all world-writable files
                        Find/list all accessible *.plan files and display contents
                        Find/list all accessible *.rhosts files and display contents
                        Show NFS server details
                        Locate *.conf and *.log files containing keyword supplied at script runtime
                        List all *.conf files located in /etc
                        Locate mail
                        Platform/software specific tests:
                        Checks to determine if we're in a Docker container
                        Checks to see if the host has Docker installed
                        Checks to determine if we're in an LXC container
                        " >> ${targetNAME}_HKP_REPORT.html
                    echo '
                        </pre>
                      </code>
                    </div>
                    <br>
                    ' >> ${targetNAME}_HKP_REPORT.html

                  }
                  HKP_PrivEsc_Checklist_HTML_Export_Template
                  # Looting for passwords
                  # Files containing passwords
                  HKP_PasSearch_HTML_Export_Template(){
                    echo '
                    <div class="row card-body gradient-border raise">
                      <h3 class="text-center glitch b2" hackbox-heading>' >> ${targetNAME}_HKP_REPORT.html
                      echo "Looting for Passwords | $(date)" >> ${targetNAME}_HKP_REPORT.html
                      echo '
                      </h3>
                      <br>
                      <code>
                        <pre>' >> ${targetNAME}_HKP_REPORT.html
                        echo " $(grep --color=auto -rnw '/' -ie "PASSWORD" --color=always 2> /dev/null)" >> ${targetNAME}_HKP_REPORT.html
                        echo " <br>" >> ${targetNAME}_HKP_REPORT.html
                        echo " $(find . -type f -exec grep -i -I "PASSWORD" {} /dev/null \;)" >> ${targetNAME}_HKP_REPORT.html
                    echo '
                        </pre>
                      </code>
                    </div>
                    <br>
                    ' >> ${targetNAME}_HKP_REPORT.html

                  }
                  HKP_PasSearch_HTML_Export_Template
                  open ${targetNAME}_HKP_REPORT.html
                  ;;
                  x|X|exit|quit|Exit )
                  clear
                  AwesomeLineExit
                  break
                  ;;
                  ls )
                  lahs
                  ;;
                esac
              done
            ;;
            # Collecting Social Information
            csi|CSI )
            while true; do
              cd "${x_Menu_1_CSI}"
              clear
              ToolHeaderRun
              TargetStatusRun
              HacKingProMenuMain=$(echo "${BRed}

    ${DGrey}┌──${BRed}[${BYellow} Collecting Social Information ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${DGrey} 00 ${BRed}]${BGreen}── ${BRed}[${DGrey} UserFinder ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${DGrey} 01 ${BRed}]${BGreen}── ${BRed}[${DGrey} E4GL30S1NT ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} X ${BRed}] 🤴 Exit / Quit / Close

    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Information Gathering ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} CSI ${BRed}]${BYellow}╼▰  ${BGreen}  ")
                read -p "$HacKingProMenuMain" cmd
                case $cmd in
                  ls )
                  lahs
                  ;;
                  x|X|exit|quit|Exit )
                  clear
                  AwesomeLineExit
                  break
                  ;;
                  0|00|uf|UF|UserFinder|userfinder )
                  cd "${MainDirectoriyCaseNameRecon}"
                  UserFinder >> "${MainDirectoriyCaseNameRecon}/${targetNAME}-UserFinder.log"
                  less -R "${MainDirectoriyCaseNameLocal}/${targetNAME}-UserFinder.log"
                  Press_ENTER
                  ;;
                esac
              done
            ;;
            # Network Information
            ni )
            net_info
            break
            ;;
            x|X|exit|quit|Exit )
            clear
            cd ${MainDirectoriy}
            AwesomeLineExit
            break
            ;;
          esac
        done
      ;;
      02|2 )
      HacKingPro_Weaponization
      ;;
      03|3 )
      while true; do
        cd "$x_Menu_3"
        clear
        ToolHeaderRun
        TargetStatusRun
        HacKingProMenuMain=$(echo "
    ${DGrey}┌──┲────╼ ${BRed}[${BYellow} Delivery ${BRed}]
    ${DGrey}|  ┖─┲──╼ ${BRed}[${BYellow} Intruder transmits the malware via a phishing email or another medium ${BRed}]
    ${DGrey}|    ┖──╼ ${BRed}[${BYellow} Intruder transmits weapon to target (e.g., via e-mail attachments, websites or USB drives) ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${BGreen} 1 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} USB ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 2 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} Email ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 3 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} WebSite ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 4 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} Message ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} X ${BRed}]${BGreen} ╼ ${BRed}[${DGrey} Exit / Quit / Close ${BRed}]


    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} 🔮 ${BRed}]${BYellow}╼▰  ${BGreen}   ")
        read -p "$HacKingProMenuMain" cmd
        case $cmd in
          ls )
          lahs
          ;;
          arsenal|Arsenal|cs|CS|cheats|Cheatsheets|CheatSheets|Commands|commands|zz )
          Arsenal
          ;;
          p|P )
          HacKingProPlanning
          ReportPlanning
          ;;
          x|X|exit|EXIT )
          cd ${MainDirectoriy}
          clear
          AwesomeLineExit
          break
          ;;
        esac
      done
      ;;
      04|4 )
      # MainAttacKing
      clear
      EnumerationPro
      Press_ENTER
      ;;
      05|5 )
      while true; do
        cd "$x_Menu_5"
        clear
        ToolHeaderRun
        TargetStatusRun

        HacKingProMenuMain=$(echo "
    ${DGrey}┌──┲────╼ ${BRed}[${BYellow} Installation ${BRed}]
    ${DGrey}|  ┖─┲──╼ ${BRed}[${BYellow} The malware installs a backdoor or other ingress accessible to the attacker ${BRed}]
    ${DGrey}|    ┖──╼ ${BRed}[${BYellow} Malware weapon installs access point (e.g., backdoor) usable by intruder. ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${BGreen} 1 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} USB ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 2 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} Email ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 3 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} WebSite ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 4 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} Message ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} X ${BRed}]${BGreen} ╼ ${BRed}[${DGrey} Exit / Quit / Close ${BRed}]


    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} 🔮 ${BRed}]${BYellow}╼▰  ${BGreen}   ")

        read -p "$HacKingProMenuMain" cmd
        case $cmd in
          ls )
          lahs
          ;;
          arsenal|Arsenal|cs|CS|cheats|Cheatsheets|CheatSheets|Commands|commands|zz )
          Arsenal
          ;;
          p|P )
          HacKingProPlanning
          ReportPlanning
          ;;
          x|X|exit|EXIT )
          cd ${MainDirectoriy}
          clear
          AwesomeLineExit
          break
          ;;
        esac
      done
      ;;
      06|6 )
      while true; do
        cd "$x_Menu_6"
        clear
        ToolHeaderRun
        TargetStatusRun

        HacKingProMenuMain=$(echo "
    ${DGrey}┌──┲────╼ ${BRed}[${BYellow} Command and Control ${BRed}]
    ${DGrey}|  ┖─┲──╼ ${BRed}[${BYellow} The intruder gains persistent access to the victim’s systems/network ${BRed}]
    ${DGrey}|    ┖──╼ ${BRed}[${BYellow} Malware enables intruder to have hands on the keyboard persistent access to target network. ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${BGreen} 1 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} USB ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 2 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} Email ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 3 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} WebSite ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 4 ${BRed}]${BGreen}───╼ ${BRed}[${BGreen} Message ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} X ${BRed}]${BGreen} ╼ ${BRed}[${DGrey} Exit / Quit / Close ${BRed}]


    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} 🔮 ${BRed}]${BYellow}╼▰  ${BGreen}   ")

        read -p "$HacKingProMenuMain" cmd
        case $cmd in
          ls )
          lahs
          ;;
          arsenal|Arsenal|cs|CS|cheats|Cheatsheets|CheatSheets|Commands|commands|zz )
          Arsenal
          ;;
          p|P )
          HacKingProPlanning
          ;;
          x|X|exit|EXIT )
          cd ${MainDirectoriy}
          clear
          AwesomeLineExit
          break
          ;;
        esac
      done
      ;;
      07|7 )
      while true; do
        cd "$x_Menu_7"
        clear
        ToolHeaderRun
        TargetStatusRun

        HacKingProMenuMain=$(echo "
    ${DGrey}┌──┲────╼ ${BRed}[${BYellow} Actions on Objective ${BRed}]
    ${DGrey}|  ┖─┲──╼ ${BRed}[${BYellow} Intruder initiates end goal actions, such as data theft, data corruption, or data destruction ${BRed}]
    ${DGrey}|    ┖──╼ ${BRed}[${BYellow} Intruder takes action to achieve their goals, such as data exfiltration, data destruction, or encryption for ransom. ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${BGreen} 1 ${BRed}]${BGreen}${faintT}───╼$resetT ${BRed}[${BGreen} USB ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 2 ${BRed}]${BGreen}${faintT}───╼$resetT ${BRed}[${BGreen} Email ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 3 ${BRed}]${BGreen}${faintT}───╼$resetT ${BRed}[${BGreen} WebSite ${BRed}]
    ${DGrey}|──${BRed}[${BGreen} 4 ${BRed}]${BGreen}${faintT}───╼$resetT ${BRed}[${BGreen} Message ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} X ${BRed}]${BGreen} ╼ ${BRed}[${DGrey} Exit / Quit / Close ${BRed}]


    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} 🔮 ${BRed}]${BYellow}╼▰  ${BGreen}   ")

        read -p "$HacKingProMenuMain" cmd
        case $cmd in
          ls )
          lahs
          ;;
          arsenal|Arsenal|cs|CS|cheats|Cheatsheets|CheatSheets|Commands|commands|zz )
          Arsenal
          ;;
          p|P )
          HacKingProPlanning
          ;;
          x|X|exit|EXIT )
          cd ${MainDirectoriy}
          clear
          AwesomeLineExit
          break
          ;;
        esac
      done
      ;;
      xp|ranger|Ranger|RangerPro )
      while true; do
        clear
        cd "${MainDirectoriyCaseName}"
        ToolHeaderRun
        TargetStatusRun
        #statements
        TargetStatus=$(echo "
    ${ORANGE}${faintT}┌──╼${resetT}${BBlue}┤${ORANGE} Xplorer Files Pro ${BBlue}├${ORANGE}${faintT}───────${resetT}${BCyan}╼▰▰▰
    ${ORANGE}${faintT}│
    ${ORANGE}${faintT}|──${resetT}${BCyan}╼▰${resetT}${BRed} [${ORANGE} 1 ${BRed}]${ORANGE}${faintT}──${resetT}${BCyan}╼▰ ${BRed}[${DGrey} XplorerPro ${BRed}]${ORANGE}${faintT}──${resetT}${BCyan}╼▰
    ${ORANGE}${faintT}|──${resetT}${BCyan}╼▰${resetT}${BRed} [${ORANGE} 2 ${BRed}]${ORANGE}${faintT}──${resetT}${BCyan}╼▰ ${BRed}[${DGrey} RangerPro ${BRed}]${ORANGE}${faintT}──${resetT}${BCyan}╼▰
    ${ORANGE}${faintT}|──${resetT}${BCyan}╼▰${resetT}${BRed} [${ORANGE} 3 ${BRed}]${ORANGE}${faintT}──${resetT}${BCyan}╼▰ ${BRed}[${DGrey} GTopPro ${BRed}]${ORANGE}${faintT}──${resetT}${BCyan}╼▰
    ${ORANGE}${faintT}│
    ${ORANGE}${faintT}└───────────────────────────────${resetT}${BCyan}╼▰▰▰

    ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BYellow}╼▰  ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Command ${BRed}]${BYellow}╼▰  ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Xplorer Files Pro ${BRed}]${BYellow}╼▰  ${BGreen}   ")
    read -p "${TargetStatus}" cmd
    case $cmd in
      1 )
      XplorerPro
      read
      ;;
      2 )
      RangerPro
      read
      ;;
      3 )
      GTopPro
      read
      ;;
      x|X|exit|quit|Exit )
      clear
      cd ${MainDirectoriy}
      AwesomeLineExit
      break
      ;;
      ls )
      lahs
      ;;
      p|P )
      HacKingProPlanning
      ;;
      cl )
      ClearTarget
      ;;
    esac
  done
      ;;
      any|Any|AnyTool|anytool )
      cd Menu
      cd AnyTool
      sh AnyTool
      cd ${MainDirectoriy}
      ;;
      arsenal|Arsenal|cs|CS|cheats|Cheatsheets|CheatSheets|Commands|commands|zz )
      Arsenal
      ;;
      p|P )
      HacKingProPlanning
      ReportPlanning
      ;;
      cl )
      ClearTarget
      ;;
      ls )
      AwesomeExplorer
      ;;
      x|X|exit|quit|Exit )
      clear
      cd ${MainDirectoriy}
      AwesomeLineExit
      break
      ;;
      r|remainder|note|td|todo)
      AwesomeToDo
      AwesomeDontForget
      Press_ENTER
      ;;
      pt|PT|pentest|PenTest ) . HacKingPro-Parts/Plugins/HacKingPro-PenTestPro;  ;;
      * )
      echo "$InvalidOption"
      ;;
    esac
  done
}
#--╼[ Main Menu ]--╼▰ [ Arsenal ]
Arsenal(){
  clear
  # Getting Arsenal Cheatsheets
  if [ -d Arsenal ]; then
    #statements
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Installed  \n"
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}cd Into Arsenal\n"
    cd Arsenal
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}List Arsenal Directories \n"
    lahs
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Runnin  \n"
    (./run)
  fi
  if [ -d $HOME/opt/anaconda3/bin/arsenal ]; then
    #statements
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Installed  \n"
    return
  else
    #statements
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Creating Folder Arsenal \n"
    mkdir Arsenal
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${LYellow}Cloning Into [./Arsenal] \n"
    git clone https://github.com/Orange-Cyberdefense/Arsenal ./Arsenal
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}cd Into Arsenal\n"
    cd Arsenal
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}List Arsenal Directories \n"
    lahs
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Installing Arsenal Requirements \n"
    python3 -m pip install -r requirements.txt
    echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Run Installation  \n"
    (./run)
    if [ "$?" == "1" ]; then
      #statements
      echo "\n\t\t ${BRed}[${LGrey}CS${BRed}]${BBlue} - ${BYellow}Arsenal Installation ${BRed} ERROR  \n"
    fi
    echo "\n\n"
    echo "\n\t\t ${BRed}[${BCyan}Readed Command${BRed}]${BBlue} - ${BYellow} $ReaDone  \n"
    Press_ENTER ArsenalCommand

  fi
  cd ..

}
#####################################
#------╼╼▰[ Main Menu ]--╼▰ [ End ] #
#####################################

#################################
#------╼╼▰[ Start ]--╼▰[ Head ] #
#################################
#--╼▰[ Start ]-╼▰ [ Main Menu ]
MainMenu
################################
#------╼╼▰[ Start ]--╼▰[ End ] #
################################

#-MetaData----------------------------------------------------#
#                                        (Update: 30-10-2022) #
#  File Name: HacKingPro                                      #
#  Aouther Name: Leon Yaakobov                                #
#  Source: https://github.com/AnLoMinus/HacKingPro            #
#                                                             #
#-Done-!------------------------------------------------------#
