language: python
os:
  # os building
  - linux
python:
  # version of python.
  - 3.7
install:
  # install packages.
  - pip install -r ./requirements.txt
before_script:
  - pip install bs4
  - pip install requests
script:
  - python Orusula.py -u http://wordpress.org
