#!/bin/bash
intarconn=$(route show | awk '(NR == 2) {print $3}')                               #                               #
MYMAC=$(ifconfig $intarconn | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')  #                               #
