#!/bin/bash
# src: https://github.com/KALILINUXTRICKSYT/easymacchanger/blob/master/easymacchanger
# EasyMacChanger



Installing(){
  chmod +x easymacchanger
cp -r easymacchanger /usr/local/sbin
echo "rm -rf /usr/local/sbin/easymacchanger && echo -e '\e[1;31m

                       (UNINSTALLATION COMPLETED)

\e[0m' && rm uninstaller.sh " > uninstaller.sh


resize -s 24 95

clear

echo -e '\e[1;32m
     ______                    __  ___
    / ____/___ ________  __   /  |/  /___ ______    \e[1;34mChange the network  \e[1;32m
   / __/ / __ `/ ___/ / / /  / /|_/ / __ `/ ___/    \e[1;34midentity of your device. \e[1;32m
  / /___/ /_/ (__  ) /_/ /  / /  / / /_/ / /__
 /_____/\__,_/____/\__, /  /_/  /_/\__,_/\___/
                  /____/                            \e[1;31mEasy Mac Changer is intented\e[1;32m
    ________                                        \e[1;31mONLY FOR EDUCATIONAL PURPOSES.\e[1;32m
   / ____/ /_  ____ _____  ____ ____  _____
  / /   / __ \/ __ `/ __ \/ __ `/ _ \/ ___/
 / /___/ / / / /_/ / / / / /_/ /  __/ /             \e[1;37mCreated by "KALI LINUX TRICKS"      \e[1;32m
 \____/_/ /_/\__,_/_/ /_/\__, /\___/_/  v1.1        \e[1;37mhttps://www.youtube.com/c/KALILINUXTRICKS \e[1;32m
                        /____/         (Linux)
\e[1;36m


                              (INSTALLATION COMPLETED)


                                                             \e[1;32m
  To execute Easy Mac Changer type anywhere in your terminal "easymacchanger".  \e[0m

'

}
i="0"

resize -s 27 96
clear
while [ $i -lt 1 ]
do

e="0"

wlan0=$(ip link show wlan0 | awk '/ether/ {print $2}')

 echo -e '\e[1;32m
     ______                    __  ___
    / ____/___ ________  __   /  |/  /___ ______    \e[1;34mChange the network  \e[1;32m
   / __/ / __ `/ ___/ / / /  / /|_/ / __ `/ ___/    \e[1;34midentity of your device. \e[1;32m
  / /___/ /_/ (__  ) /_/ /  / /  / / /_/ / /__
 /_____/\__,_/____/\__, /  /_/  /_/\__,_/\___/
                  /____/                            \e[1;31mEasy Mac Changer is intented\e[1;32m
    ________                                        \e[1;31mONLY FOR EDUCATIONAL PURPOSES.\e[1;32m
   / ____/ /_  ____ _____  ____ ____  _____
  / /   / __ \/ __ `/ __ \/ __ `/ _ \/ ___/
 / /___/ / / / /_/ / / / / /_/ /  __/ /             \e[1;37mCreated by "KALI LINUX TRICKS"      \e[1;32m
 \____/_/ /_/\__,_/_/ /_/\__, /\___/_/  v1.1        \e[1;37mhttps://www.youtube.com/c/KALILINUXTRICKS \e[1;32m
                        /____/         (Linux)

\e[1;33m
01. DELL COMPUTER                11. HP PRINTER              \e[1;36m Mac address = '$wlan0' \e[1;33m
02. APPLE LAPTOP                 12. CANON PRINTER
03. HUAWEI ANDROID PHONE         13. SAMSUNG TV
04. XIAOMI ANDROID PHONE         14. TVT CAMERA
05. SONY ANDROID PHONE           15. ZTE ROUTER
06. LG ANDROID PHONE             16. TP-LINK ROUTER           21. CUSTOM MAC ADDRESS
07. SAMSUNG ANDROID PHONE        17. OXYGEN ROUTER
08. IPOD                         18. SOLAR PANEL              22. MY ACCOUNTS - CONTACT WITH ME
09. IPAD                         19. NITENDO DS
10. IPHONE                       20. SONY PLAYSTATION 4       23. EXIT
'

dell='1'
macbook='2'
huawei='3'
xiaomi='4'
sony='5'
lg='6'
samsung='7'
ipod='8'
ipad='9'
iphone='10'
hpprinter='11'
canonprinter='12'
samsungtv='13'
tvtcamera='14'
zte='15'
tplink='16'
oxygen='17'
solarpanel='18'
nitendods='19'
ps4='20'
custommac='21'
me='22'
exit='23'





read x

if [ "$x" == "$dell" ]; then                    #dell

ifconfig wlan0 down
ifconfig wlan0 hw ether 18:03:73:E9:FB:86
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 18:03:73:E9:FB:86
ifconfig eth0 up
service network-manager restart


elif [ "$x" == "$macbook" ]; then                    #macbook

ifconfig wlan0 down
ifconfig wlan0 hw ether 00:1F:5B:C7:EE:2F
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 00:1F:5B:C7:EE:2F
ifconfig eth0 up
service network-manager restart


elif [ "$x" == "$huawei" ]; then                    #huawei

ifconfig wlan0 down
ifconfig wlan0 hw ether 8C:EB:C6:15:43:A4
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 8C:EB:C6:15:43:A4
ifconfig eth0 up
service network-manager restart


elif [ "$x" == "$xiaomi" ]; then                    #xiaomi

ifconfig wlan0 down
ifconfig wlan0 hw ether EC:D0:9F:82:EE:3F
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether EC:D0:9F:82:EE:3F
ifconfig eth0 up
service network-manager restart


elif [ "$x" == "$sony" ]; then                    #sony

ifconfig wlan0 down
ifconfig wlan0 hw ether 9C:5C:F9:3F:17:D1
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 9C:5C:F9:3F:17:D1
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$lg" ]; then                    #lg

ifconfig wlan0 down
ifconfig wlan0 hw ether BC:F5:AC:FF:38:A6
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether BC:F5:AC:FF:38:A6
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$samsung" ]; then                    #samsung

ifconfig wlan0 down
ifconfig wlan0 hw ether 8C:F5:A3:CB:14:C6
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 8C:F5:A3:CB:14:C6
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$ipod" ]; then                    #ipod

ifconfig wlan0 down
ifconfig wlan0 hw ether FC:D8:48:03:54:8C
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether FC:D8:48:03:54:8C
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$ipad" ]; then                    #ipad

ifconfig wlan0 down
ifconfig wlan0 hw ether 04:15:52:AB:6B:A4
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 04:15:52:AB:6B:A4
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$iphone" ]; then                    #iphone

ifconfig wlan0 down
ifconfig wlan0 hw ether 28:A0:2B:EC:6F:93
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 28:A0:2B:EC:6F:93
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$hpprinter" ]; then                    #hpprinter

ifconfig wlan0 down
ifconfig wlan0 hw ether D8:9D:67:DA:2F:32
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether D8:9D:67:DA:2F:32
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$canonprinter" ]; then                    #canonprinter

ifconfig wlan0 down
ifconfig wlan0 hw ether 00:00:85:D2:01:4A
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 00:00:85:D2:01:4A
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$samsungtv" ]; then                    #samsungtv

ifconfig wlan0 down
ifconfig wlan0 hw ether F8:77:B8:0C:49:B1
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether F8:77:B8:0C:49:B1
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$tvtcamera" ]; then                    #tvtcamera

ifconfig wlan0 down
ifconfig wlan0 hw ether 00:18:AE:63:81:70
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 00:18:AE:63:81:70
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$zte" ]; then                    #zte

ifconfig wlan0 down
ifconfig wlan0 hw ether 34:4D:EA:87:8A:F8
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 34:4D:EA:87:8A:F8
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$tplink" ]; then                    #tplink

ifconfig wlan0 down
ifconfig wlan0 hw ether 00:14:78:53:01:D8
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 00:14:78:53:01:D8
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$oxygen" ]; then                    #oxygen

ifconfig wlan0 down
ifconfig wlan0 hw ether 00:1d:1c:06:b5:ee
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 00:1d:1c:06:b5:ee
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$solarpanel" ]; then                    #solarpanel

ifconfig wlan0 down
ifconfig wlan0 hw ether 00:27:02:04:06:08
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 00:27:02:04:06:08
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$nitendods" ]; then                    #nitendods

ifconfig wlan0 down
ifconfig wlan0 hw ether 00:1D:BC:C9:CC:ED
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether 00:1D:BC:C9:CC:ED
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$ps4" ]; then                    #ps4

ifconfig wlan0 down
ifconfig wlan0 hw ether F8:46:1C:0D:27:1B
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether F8:46:1C:0D:27:1B
ifconfig eth0 up
service network-manager restart



elif [ "$x" == "$custommac" ]; then                 #custommac


read -p 'Type mac address (example AA:AA:AA:AA:AA:AA) : '  m



ifconfig wlan0 down
ifconfig wlan0 hw ether $m
ifconfig wlan0 up
ifconfig eth0 down
ifconfig eth0 hw ether $m
ifconfig eth0 up
service network-manager restart

sleep 3

e=1

clear


elif [ "$x" == "$me" ]; then                 #CONTACT WITH ME

clear

resize -s 32 54

clear

echo -e '\e[1;33m
     ______                    __  ___
    / ____/___ ________  __   /  |/  /___ ______
   / __/ / __ `/ ___/ / / /  / /|_/ / __ `/ ___/
  / /___/ /_/ (__  ) /_/ /  / /  / / /_/ / /__
 /_____/\__,_/____/\__, /  /_/  /_/\__,_/\___/
                  /____/
    ________
   / ____/ /_  ____ _____  ____ ____  _____
  / /   / __ \/ __ `/ __ \/ __ `/ _ \/ ___/
 / /___/ / / / /_/ / / / / /_/ /  __/ /
 \____/_/ /_/\__,_/_/ /_/\__, /\___/_/  v1.1
                        /____/         (Linux)
 \e[1;31m


 https://www.youtube.com/c/KALILINUXTRICKS
 \e[1;32m
 https://github.com/KALILINUXTRICKSYT
 \e[1;34m
 https://www.twitter.com/KALILINUXTRICKS
 \e[1;35m
 https://www.instagram.com/kali_linux_tricks_youtube
 \e[1;33m
 https://www.patreon.com/kalilinuxtricks
 \e[1;37m
 kalilinuxtricks@gmail.com


              Press ENTER to Main Menu
'
read

e=1

resize -s 27 96
clear

elif [ "$x" == "$exit" ]; then                 #exit

exit



else

e=1





echo -e ' \e[1;31m
 _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |
|_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_|
(_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_)

 ####### #     # ######  #######    #     # ####### ######  #######
    #     #   #  #     # #          ##   ## #     # #     # #
    #      # #   #     # #          # # # # #     # #     # #
    #       #    ######  #####      #  #  # #     # ######  #####
    #       #    #       #          #     # #     # #   #   #
    #       #    #       #          #     # #     # #    #  #
    #       #    #       #######    #     # ####### #     # #######

  #####     #    ######  ####### ####### #     # #       #       #     #
 #     #   # #   #     # #       #       #     # #       #        #   #
 #        #   #  #     # #       #       #     # #       #         # #
 #       #     # ######  #####   #####   #     # #       #          #
 #       ####### #   #   #       #       #     # #       #          #
 #     # #     # #    #  #       #       #     # #       #          #
  #####  #     # #     # ####### #        #####  ####### #######    #
 _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |
|_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_|
(_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_)
'


fi



if [ "$e" == 0 ]; then





echo -e '\e[1;32m
   __  __
   \ \/ /___  __  _______   ____ ___  ____ ______
    \  / __ \/ / / / ___/  / __ `__ \/ __ `/ ___/
    / / /_/ / /_/ / /     / / / / / / /_/ / /__
   /_/\____/\__,_/_/     /_/ /_/ /_/\__,_/\___/

                __    __                       __
     ____ _____/ /___/ /_______  __________   / /_  ____ ______
    / __ `/ __  / __  / ___/ _ \/ ___/ ___/  / __ \/ __ `/ ___/
   / /_/ / /_/ / /_/ / /  /  __(__  |__  )  / / / / /_/ (__  )
   \__,_/\__,_/\__,_/_/   \___/____/____/  /_/ /_/\__,_/____/

           __                               __
     _____/ /_  ____ _____  ____ ____  ____/ /
    / ___/ __ \/ __ `/ __ \/ __ `/ _ \/ __  /
   / /__/ / / / /_/ / / / / /_/ /  __/ /_/ /
   \___/_/ /_/\__,_/_/ /_/\__, /\___/\__,_/
                         /____/
                                           ____      ____
      _______  _______________  __________/ __/_  __/ / /_  __
     / ___/ / / / ___/ ___/ _ \/ ___/ ___/ /_/ / / / / / / / /
    (__  ) /_/ / /__/ /__/  __(__  |__  ) __/ /_/ / / / /_/ /
   /____/\__,_/\___/\___/\___/____/____/_/  \__,_/_/_/\__, /
                                                     /____/   \e[0m
'

sleep 4

clear


fi






done
