codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "40...50"
  status:
    patch: no
    changes: no
    project:
      default:
        threshold: 2%
        paths: 
        - "ciphey"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
