#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-Planning ]                #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 15-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 15-08-2022 ]                              #
###############################################################

########################################################
#------╼╼▰[ HacKingPro ]--╼▰▰[ Planning ]--╼▰ [ Head ] #
########################################################
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]
HacKingProPlanning(){
  clear
  ToolHeaderRun
  TargetStatusRun
  cd "${MainDirectoriyCase}"

  AwesomeLine "Planning"
  ReadTargetNameFromtheUser
  ReadTargetIPFromtheUser
  ReadTargetURLFromtheUser
  ReadTargetEmailFromtheUser
  ReadTargetPhoneFromtheUser
  AwesomeLine "Planning"

  mkdir "${MainDirectoriyCaseName}"
  cd "${MainDirectoriyCaseName}"
  # Define Target Case Name Planning {Variable}
  MainDirectoriyCaseNamePlanning="${MainDirectoriyCaseName}/Planning"
  # Create Target Case Name Planning Folder
  mkdir "${MainDirectoriyCaseNamePlanning}"
  cd "${MainDirectoriyCaseNamePlanning}"

  # Define Target Case Name Recon {Variable}
  MainDirectoriyCaseNameRecon="${MainDirectoriyCaseName}/Recon"
  # Create Target Case Name Recon {Folder}
  mkdir "${MainDirectoriyCaseNameRecon}"


  # User_WordlistLocation
  # ReadUserNameFromtheUser

  # Pass_WordlistLocation
  # ReadUserPassFromtheUser

  # Listing Case Contents
  AwesomeLine "Listing Case"
  echo "          ${BYellow} Log Directory ${BRed}[${BGreen} ${MainDirectoriyCase} ${BRed}]"
  echo "\n"; ls -lahs ${MainDirectoriyCase} ;
  echo "          ${BYellow} Log File ${BRed}[${BGreen}\n $(pwd) ${BRed}\n]\n${BGreen}"
  echo "\n"; pwd;
  AwesomeLine "Listing Case"
  Press_ENTER
}
#-╼▰[ HacKingPro ]-╼▰▰[ Android Planning ]
AndroidPlan(){
  while  true; do
    #statements
    # cd "${MainDirectoriyCaseNameRecon}"
    # mkdir "${MainDirectoriyCaseNameRecon}/Android"
    clear
    cd "${x_Menu_2_Android}"
    ToolHeaderRun
    TargetStatusRun
    AndroidPlanningMainMenu="$(echo "
    ${BGreen}${faintT}┌──${resetT}${BGreen}╼▰${BGreen}${faintT}┤${resetT}${BGreen}${slowBlink} Android Planning ${resetT}${BGreen}${faintT}├${resetT}${BGreen}${faintT}───────${resetT}${BGreen}╼▰▰▰
    ${BGreen}${faintT}│
    ${BGreen}${faintT}|──${resetT}${BGreen}╼▰ ${resetT}${BRed}[${DGrey}$(FunTargetIP)${BRed}]${BGreen}${faintT}──${resetT}${BGreen}╼▰
    ${BGreen}${faintT}|──${resetT}${BGreen}╼▰ ${resetT}${BRed}[${DGrey}$(FunTargetName)${BRed}]${BGreen}${faintT}──${resetT}${BGreen}╼▰
    ${BGreen}${faintT}|──${resetT}${BGreen}╼▰ ${resetT}${BRed}[${DGrey}$(FunTargetPhone)${BRed}]${BGreen}${faintT}──${resetT}${BGreen}╼▰
    ${BGreen}${faintT}│
    ${BGreen}${faintT}└───────────────────────────────${resetT}${BGreen}╼▰▰▰

    ")"
  read -p "${AndroidPlanningMainMenu}" cmd
  case $cmd in
    x|X|exit|quit|Exit )
    clear
    cd ${MainDirectoriy}
    AwesomeLineExit
    break
    ;;
    p|P )
    HacKingProPlanning
    ;;
    cl )
    ClearTarget
    ;;
    ls )
    lahs
    ;;
    * )
    echo "$InvalidOption"
    ;;
  esac
done
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]--╼▰[ Target ]--╼▰[ Name ]
ReadTargetNameFromtheUser(){
  # Read Target Name From the User
  # This Variable is for Case Name.
  t0="$(echo "\n          ${BBlue}┌──[ 🎯 ]──[${BRed} Name ${BBlue}]──╼  ")"
  read -p "$t0" targetNAME
  if [ -z "$targetNAME" ]; then
    #statements
    targetNAME="AnLoMinus"
    # echo "\n\t  ${BRed}[${LGrey}TN${BRed}]${BBlue} - ${LGrey}Target Name ${BBlue} $targetNAME\n"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]--╼▰[ Target ]--╼▰[ IP ]
ReadTargetIPFromtheUser(){
# Read Target IP
# This Variable is for AttacKing ~> IP Addresses .
t1="$(echo "\n          ${BBlue}|──[ 🎯 ]──[${BRed} IP ${BBlue}]──╼  ")"
read -p "$t1" targetIP

if [ -z ${targetIP} ]; then
  if [ ! -z ${targetDns} ]; then
    #statements
    GetIP="$(ping -c 1 "${targetDns}" | grep ttl | cut -d " " -f4 |  tr  -d :)"
    targetIP="${GetIP}"
  fi
  #statements
  if [ -z "$targetIP" ]; then
    #statements
    targetIP="127.0.0.1"
    # targetIP=" "
  fi
fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]--╼▰[ Target ]--╼▰[ URL ]
ReadTargetURLFromtheUser(){
# Read Target URL / Domain / Dns / Server From the User
# This Variable is for OSINT and AttacKing ~> URL / Domain / Dns / Server/ Websites .
t2="$(echo "\n          ${BBlue}|──[ 🎯 ]──[${BRed} URL ${BBlue}]──╼  ")"
read -p "$t2" targetDns
if [ ! -z "$targetDns" ]; then
  #statements
  GetIP="$(ping -c 1 "${targetDns}" | grep ttl | cut -d " " -f4 |  tr  -d :)"
  targetIP="${GetIP}"
else
  targetDns="xXx.AnLoMinus.xXx"
fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]--╼▰[ Target ]--╼▰[ Email ]
ReadTargetEmailFromtheUser(){

# This Variable is for OSINT and AttacKing ~> Emails .
t3="$(echo "\n          ${BBlue}|──[ 🎯 ]──[${BRed} Email ${BBlue}]──╼  ")"
read -p "$t3" targetEmail
if [ -z $targetEmail ]; then
  #statements
  targetEmail="Change.Me@Do.Now"
  # echo "\n${BRed}[${LGrey}TE${BRed}]${BBlue} - ${LGrey}Target Email ${BBlue} $targetEmail\n"
fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]--╼▰[ Target ]--╼▰[ Phone ]
ReadTargetPhoneFromtheUser(){

# This Variable is for OSINT and AttacKing ~> Phones Numbers .
t4="$(echo "\n          ${BBlue}└──[ 🎯 ]──[${BRed} Phone (With Country Code) ${BBlue}]──╼  ")"
read -p "$t4" targetPhone
if [ -z "$targetPhone" ]; then
  #statements
  targetPhone="9720506933037"
  # echo "\n${BRed}[${LGrey}TP${BRed}]${BBlue} - ${LGrey}Target Phone ${BBlue} $targetPhone\n"
fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]--╼▰[ User ]--╼▰[ Password ]
ReadUserPassFromtheUser(){
  readUserPass="$(echo "    Enter Password: ")"
  echo "\n"
  read -p "${readUserPass}" UserPass
  echo "\n"
  if [ -z "${UserPass}" ]; then
    UserPass="PassWord"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]--╼▰[ User ]--╼▰[ Name ]
ReadUserNameFromtheUser(){
  readUserName="$(echo "    Enter UserName: ")"
  echo "\n"
  read -p "${readUserName}" UserName
  echo "\n"
  if [ -z "${UserName}" ]; then
    UserName="Admin"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]--╼▰[ Users List ]
User_WordlistLocation(){
  readUsersWordList="$(echo "    Enter Users WordList Location: ")"
  echo "\n"
  read -p "${readUsersWordList}" UserWordList
  echo "\n"
  if [ -z "${UserWordList}" ]; then
    if [ -e "User.txt" ]; then
      #statements
      echo "\n"
      echo "    ${BGreen}Found ${BWhite}User.txt"
      echo "\n"
    else
      echo "\n"
      echo "    ${BRed}Not Found ${BWhite}User.txt"
      echo "\n"
      # wget https://github.com/Cryilllic/Active-Directory-Wordlists/blob/master/User.txt
    fi
    UserWordList="User.txt"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Read ]--╼▰[ Passwords List ]
Pass_WordlistLocation(){
  readPasswordsWordList="$(echo "    Enter Passwords WordList Location: ")"
  echo "\n"
  read -p "${readPasswordsWordList}" PassWordList
  echo "\n"
  if [ -z "${PassWordList}" ]; then
    if [ -e "Pass.txt" ]; then
      #statements
      echo "\n"
      echo "    ${BGreen}Found ${BWhite}Pass.txt"
      echo "\n"
    else
      echo "\n"
      echo "    ${BRed}Not Found ${BWhite}Pass.txt"
      echo "\n"
      # wget https://github.com/Cryilllic/Active-Directory-Wordlists/blob/master/Pass.txt
    fi
    PassWordList="Pass.txt"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Target ]--╼▰[ Planning Status ]--╼▰[ Dns ]
FunTargetDns(){
  #statements
  if [ -z ${targetDns} ]; then
    TargetDnsStatusOFF=" ❌ "
    echo "${TargetDnsStatusOFF}"
  else
    targetDnsStatusON=" ✅ "
    echo "${targetDnsStatusON}"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Target ]--╼▰[ Planning Status ]--╼▰[ IP ]
FunTargetIP(){
  #statements
  if [ -z ${targetIP} ]; then
    TargetIpStatusOFF=" ❌ "
    echo "${TargetIpStatusOFF}"
  else
    TargetIpStatusON=" ✅ "
    echo "${TargetIpStatusON}"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Target ]--╼▰[ Planning Status ]--╼▰[ Name ]
FunTargetName(){
  #statements
  if [ -z ${targetNAME} ]; then
    TargetNameStatusOFF=" ❌ "
    echo "${TargetNameStatusOFF}"
  else
    TargetNameStatusON=" ✅ "
    echo "${TargetNameStatusON}"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Target ]--╼▰[ Planning Status ]--╼▰[ Email ]
FunTargetEmail(){
  #statements
  if [ -z ${targetEmail} ]; then
    TargetEmailStatusOFF=" ❌ "
    echo "${TargetEmailStatusOFF}"
  else
    TargetEmailStatusON=" ✅ "
    echo "${TargetEmailStatusON}"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Target ]--╼▰[ Planning Status ]--╼▰[ Phone ]
FunTargetPhone(){
      #statements
      if [ -z ${targetPhone} ]; then
        TargetPhoneStatusOFF=" ❌ "
        echo "${TargetPhoneStatusOFF}"
      else
        TargetPhoneStatusON=" ✅ "
        echo "${TargetPhoneStatusON}"
      fi
    }
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Target ]--╼▰[ Planning Status ]--╼▰[ Dns ]
FunTargetUserWordlist(){
      #statements
      if [ -z ${UserWordList} ]; then
        TargetUserWordListStatusOFF=" ❌ "
        echo "${TargetUserWordListStatusOFF}"
      else
        TargetUserWordListStatusON=" ✅ "
        echo "${TargetUserWordListStatusON}"
      fi
    }
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Target ]--╼▰[ Planning Status ]--╼▰[ Dns ]
FunTargetPassWordlist(){
      #statements
      if [ -z ${PassWordList} ]; then
        TargetPassWordListStatusOFF=" ❌ "
        echo "${TargetPassWordListStatusOFF}"
      else
        TargetPassWordListStatusON=" ✅ "
        echo "${TargetPassWordListStatusON}"
      fi
    }
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Target ]--╼▰[ Planning Status ]--╼▰[ Dns ]
FunTargetUserName(){
      #statements
      if [ -z ${UserName} ]; then
        TargetUserNameStatusOFF=" ❌ "
        echo "${TargetUserNameStatusOFF}"
      else
        TargetUserNameStatusON=" ✅ "
        echo "${TargetUserNameStatusON}"
      fi
    }
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Target ]--╼▰[ Planning Status ]--╼▰[ Dns ]
FunTargetUserPass(){
  #statements
  if [ -z ${UserPass} ]; then
    TargetUserPassStatusOFF=" ❌ "
    echo "${TargetUserPassStatusOFF}"
  else
    TargetUserPassStatusON=" ✅ "
    echo "${TargetUserPassStatusON}"
  fi
}
#-╼▰[ HacKingPro ]-╼▰▰[ Planning ]--╼▰[ Clear Target Variables ]
ClearTarget(){
echo "\n\n"
echo "    ┌──[ cl ]──╼ [ ⚡️ 🧹 Cleaning Target Variables  🧹 ]"
sleep 0.3
echo "    |"
echo "    |──[ 🧹 ]──[ ✅ ]──╼  IP:  "
targetIP=" "
sleep 0.2
echo "    |──[ 🧹 ]──[ ✅ ]──╼  Dns:  "
targetDns=" "
sleep 0.2
echo "    |──[ 🧹 ]──[ ✅ ]──╼  Name:  "
targetNAME=" "
sleep 0.2
echo "    |──[ 🧹 ]──[ ✅ ]──╼  Email:  "
targetEmail=" "
sleep 0.2
echo "    |──[ 🧹 ]──[ ✅ ]──╼  Phone:  "
targetPhone=" "
sleep 0.2
echo "    |──[ 🧹 ]──[ ✅ ]──╼  UserName:  "
UserName=" "
sleep 0.2
echo "    |──[ 🧹 ]──[ ✅ ]──╼  UserPass:  "
UserPass=" "
sleep 0.2
echo "    |──[ 🧹 ]──[ ✅ ]──╼  Users WordList:  "
UserWordList=" "
sleep 0.2
echo "    |──[ 🧹 ]──[ ✅ ]──╼  Passwords WordList:  "
PassWordList=" "
sleep 0.3
echo "    |"
echo "    └──[ DONE ]──╼ [ Cleaning DONE ! ]"

  Press_ENTER

}
#######################################################
#------╼╼▰[ HacKingPro ]--╼▰▰[ Planning ]--╼▰ [ End ] #
#######################################################
