#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-Installer ]               #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 15-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 15-08-2022 ]                              #
###############################################################

########################################################################
#------╼╼▰[ Variables ]--╼▰ [ HacKingPro ]--╼▰ [ Colors ]--╼▰ [ Head ] #
########################################################################
#-╼╼▰[ Variables ]--╼▰ [ HacKingPro--╼▰ [ Colors ]
# HacKingProColors(){
#
# ###############################################
# # Text Attributes
# ###############################################
#
# # Reset text formatting and colors.
# resetT="\033[m"
# # Bold text
# boldT="\033[1m"
# # Faint text.
# faintT="\033[2m"
# # Italic text.
# italicT="\033[3m"
# # Underline text.
# underT="\033[4m"
# # Slow blink.
# slowBlink="\033[5m"
# # Swap foreground and background colors.
# swapFandBC="\033[7m"
# # Hidden text.
# hidden="\033[8m"
# # Strike-through text.
# strikeThroughT="\033[9m"
#
# ##############################################################################
# # COLORS AND BACKGROUNDS
# ##############################################################################
# Color_Off='\033[0m' # Text Reset
# ORANGE='\033[1;38;5;202m'
#
# C=$(printf '\033')
# RED="${C}[1;31m"
# SED_RED="${C}[1;31m&${C}[0m"
# GREEN="${C}[1;32m"
# SED_GREEN="${C}[1;32m&${C}[0m"
# YELLOW="${C}[1;33m"
# SED_YELLOW="${C}[1;33m&${C}[0m"
# SED_RED_YELLOW="${C}[1;31;103m&${C}[0m"
# BLUE="${C}[1;34m"
# SED_BLUE="${C}[1;34m&${C}[0m"
# ITALIC_BLUE="${C}[1;34m${C}[3m"
# LIGHT_MAGENTA="${C}[1;95m"
# SED_LIGHT_MAGENTA="${C}[1;95m&${C}[0m"
# LIGHT_CYAN="${C}[1;96m"
# SED_LIGHT_CYAN="${C}[1;96m&${C}[0m"
# LG="${C}[1;37m" #LightGray
# SED_LG="${C}[1;37m&${C}[0m"
# DG="${C}[1;90m" #DarkGray
# SED_DG="${C}[1;90m&${C}[0m"
# NC="${C}[0m"
# UNDERLINED="${C}[5m"
# ITALIC="${C}[3m"
#
# # Regular Colors
# Black='\033[0;30m'  # Black
# Red='\033[0;31m'    # Red
# Green='\033[0;32m'  # Green
# Yellow='\033[0;33m' # Yellow
# Blue='\033[0;34m'   # Blue
# Purple='\033[0;35m' # Purple
# Cyan='\033[0;36m'   # Cyan
# White='\033[0;97m'  # White
#
# # Additional colors
# LGrey='\033[0;37m'   # Ligth Gray
# DGrey='\033[0;90m'   # Dark Gray
# LRed='\033[0;91m'    # Ligth Red
# LGreen='\033[0;92m'  # Ligth Green
# LYellow='\033[0;93m' # Ligth Yellow
# LBlue='\033[0;94m'   # Ligth Blue
# LPurple='\033[0;95m' # Light Purple
# LCyan='\033[0;96m'   # Ligth Cyan
#
#
# # Bold
# BBlack='\033[1;30m'  # Black
# BRed='\033[1;31m'    # Red
# BGreen='\033[1;32m'  # Green
# BYellow='\033[1;33m' # Yellow
# BBlue='\033[1;34m'   # Blue
# BPurple='\033[1;35m' # Purple
# BCyan='\033[1;36m'   # Cyan
# BWhite='\033[1;37m'  # White
#
# # Underline
# UBlack='\033[4;30m'  # Black
# URed='\033[4;31m'    # Red
# UGreen='\033[4;32m'  # Green
# UYellow='\033[4;33m' # Yellow
# UBlue='\033[4;34m'   # Blue
# UPurple='\033[4;35m' # Purple
# UCyan='\033[4;36m'   # Cyan
# UWhite='\033[4;37m'  # White
#
# # Background
# On_Black='\033[40m'  # Black
# On_Red='\033[41m'    # Red
# On_Green='\033[42m'  # Green
# On_Yellow='\033[43m' # Yellow
# On_Blue='\033[44m'   # Blue
# On_Purple='\033[45m' # Purple
# On_Cyan='\033[46m'   # Cyan
# On_White='\033[47m'  # White
# }
# HacKingProColors

########################################################################
#------╼╼▰[ Variables ]--╼▰ [ HacKingPro ]--╼▰ [ Colors ]--╼▰ [ Head ] #
########################################################################
#-╼╼▰[ Variables ]--╼▰ [ HacKingPro--╼▰ [ Colors ]
HacKingProColors(){

###############################################
# Text Attributes
###############################################

# Reset text formatting and colors.
resetT="\033[m"
# Faint text.
faintT="\033[2m"
# Slow blink.
slowBlink="\033[5m"

Color_Off='\033[0m' # Text Reset
ORANGE='\033[1;38;5;202m'

# Light
LGrey='\033[0;37m'   # Ligth Gray
DGrey='\033[0;90m'   # Dark Gray
LRed='\033[0;91m'    # Ligth Red
LGreen='\033[0;92m'  # Ligth Green
LYellow='\033[0;93m' # Ligth Yellow
LBlue='\033[0;94m'   # Ligth Blue
LCyan='\033[0;96m'   # Ligth Cyan

# Bold
BRed='\033[1;31m'    # Red
BGreen='\033[1;32m'  # Green
BYellow='\033[1;33m' # Yellow
BBlue='\033[1;34m'   # Blue
BCyan='\033[1;36m'   # Cyan
BWhite='\033[1;37m'  # White

}
HacKingProColors
#######################################################################
#------╼╼▰[ Variables ]--╼▰ [ HacKingPro ]--╼▰ [ Colors ]--╼▰ [ End ] #
#######################################################################
