name: Tests
on: [push, pull_request]
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
        os: [ubuntu-latest, windows-latest] #macos-latest,
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: python -m pip install --upgrade pip
    - run: pip install codespell flake8 nox poetry
    - run: codespell --ignore-words-list="nd,te" --skip="translations,*.archive"
    - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - run: python -m nox
