#!/bin/sh
#!/bin/bash
#!/usr/bin/bash
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/bash
###############################################
Anlominus="Anlominus"
# Name : Anlominus ~ HacKingPro
# Description : HacKingPro ~ enter your target and Hack Him and get Markdown Report.
# Date : 2022 May
# Last UPDATE : 2022 May 27
# Aouther: Anlominus ~> RhytMix ~> HacKingPro
# Skils: Best Copywriter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: To All World Creators free Scripts & Tools
# Location: Made With LOVE IN ISRAEL !
# Source: https://github.com/Anlominus/HacKingPro
###############################################
gitlist() (
clear
pwd
mkdir GiTools
cd GiTools
pwd
sleep 1
echo "[🔸] Installing Tools ~ `date`"  >>  GiTools.log
echo "[🔹] [04] - SubDomain Information"

if [$? == 0] then;

echo "[🔸] [✅] [E4GL30S1NT]" >> GiTools.log; git clone https://github.com/C0MPL3XDEV/E4GL30S1NT >>  GiTools.log
echo "[🔸] [✅] [Photon]" >> GiTools.log; git clone https://github.com/s0md3v/Photon >>  GiTools.log

)
gitlist
