#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                        Figlet Fonts                         #
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-Figlet ]                  #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 24-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 24-08-2022 ]                              #
###############################################################

Figlet_Show(){
  #!bin/sh

clear
echo "\033[1;91m---------------------------------------------------------"
figlet -f Puffy "LazyFiglet"
echo " Generate figlet fonts in Easy way with LazyFiglet By Bibek sah"
echo " "
echo "        Author Information"
echo " => Name    : Bibek sah"
echo " => Github  : https://github.com/ExpertAnonymous/LazyFiglet"
echo " => YouTube : www.youtube.com/ExpertAnonymousOfficial"
echo " => WhatsApp: Expert Anonymous"
echo "-------------------------------------------------------------- "
echo " "

echo -n "\033[1;93m[*] Enter Your Name : "
read a
if [ ! -z $a ]
then

echo " "
echo -n "\033[1;96m[*] This LazyFiglet Script By < Expert Anonymous "
echo " "
echo -n "\033[1;92m Fonts Generating.... "

echo ""
echo ""
echo "Font = 1Row "

figlet -f 1Row $a


echo "Font = 3-D "

figlet -f 3-D $a


echo "Font = D-ASCII "

figlet -f 3D-ASCII $a


echo "Font = 4Max "

figlet -f 4Max $a


echo "Font = Acrobatic "

figlet -f Acrobatic $a


echo "Font = Alligator2 "

figlet -f Alligator2 $a


echo "Font = Alpha "

figlet -f Alpha $a


echo "Font = Alphabet "

figlet -f Alphabet $a


echo "Font = Arrows "

figlet -f Arrows $a


echo "Font = Avatar "

figlet -f Avatar $a


echo "Font = B1FF "

figlet -f B1FF $a


echo "Font = Banner "

figlet -f Banner $a


echo "Font = Banner3 "

figlet -f Banner3 $a


echo "Font = Banner4 "

figlet -f Banner4 $a


echo "Font = Barbwire "

figlet -f Barbwire $a


echo "Font = Basic "

figlet -f Basic $a


echo "Font = Bear "

figlet -f Bear $a


echo "Font = Bell "

figlet -f Bell $a


echo "Font = Benjamin "

figlet -f Benjamin $a


echo "Font = Big "

figlet -f Big $a


echo "Font = Bigfig "

figlet -f Bigfig $a


echo "Font = Binary "

figlet -f Binary $a


echo "Font = Block "

figlet -f Block $a


echo "Font = Blocks "

figlet -f Blocks $a


echo "Font = Bolger "

figlet -f Bolger $a


echo "Font = Braced "

figlet -f Braced $a


echo "Font = Bright "

figlet -f Bright $a


echo "Font = Broadway "

figlet -f Broadway $a


echo "Font = Broadway KB "

figlet -f Broadway KB $a


echo "Font = Bubble "

figlet -f Bubble $a


echo "Font = Bulbhead "

figlet -f Bulbhead $a


echo "Font = Caligraphy "

figlet -f Caligraphy $a


echo "Font = Caligraphy2 "

figlet -f Caligraphy2 $a


echo "Font = Cards "

figlet -f Cards $a


echo "Font = Catwalk "

figlet -f Catwalk $a


echo "Font = Chiseled "

figlet -f Chiseled $a


echo "Font = Chunky "

figlet -f Chunky $a


echo "Font = Coinstak "

figlet -f Coinstak $a


echo "Font = Cola "

figlet -f Cola $a


echo "Font = Colossal "

figlet -f Colossal $a


echo "Font = Computer "

figlet -f Computer $a


echo "Font = Contessa "

figlet -f Contessa $a


echo "Font = Contrast "

figlet -f Contrast $a


echo "Font = Cosmike "

figlet -f Cosmike $a


echo "Font = Crawford "

figlet -f Crawford $a


echo "Font = Crawford2 "

figlet -f Crawford2 $a


echo "Font = Crazy "

figlet -f Crazy $a


echo "Font = Cricket "

figlet -f Cricket $a


echo "Font = Cursive "

figlet -f Cursive $a


echo "Font = Cyberlarge "

figlet -f Cyberlarge $a


echo "Font = Cybersmall "

figlet -f Cybersmall $a


echo "Font = Cygnet "

figlet -f Cygnet $a


echo "Font = DANC4 "

figlet -f DANC4 $a


echo "Font = DWhistled "

figlet -f DWhistled $a


echo "Font = Decimal "

figlet -f Decimal $a


echo "Font = Diamond "

figlet -f Diamond $a


echo "Font = Digital "

figlet -f Digital $a


echo "Font = Doh "

figlet -f Doh $a


echo "Font = Doom "

figlet -f Doom $a


echo "Font = Double "

figlet -f Double $a


echo "Font = Elite "

figlet -f Elite $a


echo "Font = Epic "

figlet -f Epic $a


echo "Font = Fender "

figlet -f Fender $a


echo "Font = Flipped "

figlet -f Flipped $a


echo "Font = Fraktur "

figlet -f Fraktur $a


echo "Font = Fuzzy "

figlet -f Fuzzy $a


echo "Font = Georgi16 "

figlet -f Georgi16 $a


echo "Font = Ghost "

figlet -f Ghost $a


echo "Font = Ghoulish "

figlet -f Ghoulish $a


echo "Font = Glenyn "

figlet -f Glenyn $a


echo "Font = Gothic "

figlet -f Gothic $a


echo "Font = Graceful "

figlet -f Graceful $a


echo "Font = Gradient "

figlet -f Gradient $a


echo "Font = Graffiti "

figlet -f Graffiti $a


echo "Font = Greek "

figlet -f Greek $a


echo "Font = Hex"

figlet -f Hex $a


echo "Font = Hieroglyphs "

figlet -f Hieroglyphs $a


echo "Font = Hollywood "

figlet -f Hollywood $a


echo "Font = ICL-1900 "

figlet -f ICL-1900 $a


echo "Font = Impossible "

figlet -f Impossible $a


echo "Font = Invita "

figlet -f Invita $a


echo "Font = Isometric1 "

figlet -f Isometric1 $a


echo "Font = Isometric2 "

figlet -f Isometric2 $a


echo "Font = Isometric3 "

figlet -f Isometric3 $a


echo "Font = Isometric4 "

figlet -f Isometric4 $a


echo "Font = Italic "

figlet -f Italic $a


echo "Font = Ivrit "

figlet -f Ivrit $a


echo "Font = Jacky "

figlet -f Jacky $a


echo "Font = Jazmine "

figlet -f Jazmine $a


echo "Font = Jerusalem "

figlet -f Jerusalem $a


echo "Font = Katakana "

figlet -f Katakana $a


echo "Font = Kban "

figlet -f Kban $a


echo "Font = Keyboard "

figlet -f Keyboard $a


echo "Font = Knob "

figlet -f Knob $a


echo "Font = Konto "

figlet -f Konto $a


echo "Font = LCD"

figlet -f LCD $a


echo "Font = Lean "

figlet -f Lean $a


echo "Font = Letters "

figlet -f Letters $a


echo "Font = Linux "

figlet -f Linux $a


echo "Font = Lockergnome "

figlet -f Lockergnome $a


echo "Font = Madrid "

figlet -f Madrid $a


echo "Font = Marquee "

figlet -f Marquee $a


echo "Font = Maxfour "

figlet -f Maxfour $a


echo "Font = Merlin1 "

figlet -f Merlin1 $a


echo "Font = Merlin2 "

figlet -f Merlin2 $a


echo "Font = Mike "

figlet -f Mike $a


echo "Font = Mirror "

figlet -f Mirror $a


echo "Font = Mnemonic "

figlet -f Mnemonic $a


echo "Font = Modular "

figlet -f Modular $a


echo "Font = Morse "

figlet -f Morse $a


echo "Font = Morse2 "

figlet -f Morse2 $a


echo "Font = Moscow "

figlet -f Moscow $a


echo "Font = Mshebrew210 "

figlet -f Mshebrew210 $a


echo "Font = Muzzle "

figlet -f Muzzle $a


echo "Font = NScript "

figlet -f NScript $a


echo "Font = Nancyj-Fancy "

figlet -f Nancyj-Fancy $a


echo "Font = Nancyj-Improved "

figlet -f Nancyj-Improved $a


echo "Font = Nancyj "

figlet -f Nancyj $a


echo "Font = Nipples "

figlet -f Nipples $a


echo "Font = OS2 "

figlet -f OS2 $a


echo "Font = Octal "

figlet -f Octal $a


echo "Font = Ogre "

figlet -f Ogre $a


echo "Font = Patorjk-HeX "

figlet -f Patorjk-HeX $a


echo "Font = Pawp "

figlet -f Pawp $a


echo "Font = Peaks "

figlet -f Peaks $a


echo "Font = Poison "

figlet -f Poison $a


echo "Font = Puffy "

figlet -f Puffy $a


echo "Font = Pzzle "

figlet -f Puzzle $a


echo "Font = Pyramid "

figlet -f Pyramid $a


echo "Font = Rammstein "

figlet -f Rammstein $a


echo "Font = Rectangles "

figlet -f Rectangles $a


echo "Font = Relief "

figlet -f Relief $a


echo "Font = Relief2 "

figlet -f Relief2 $a


echo "Font = Reverse "

figlet -f Reverse $a


echo "Font = Roman "

figlet -f Roman $a


echo "Font = Rot13 "

figlet -f Rot13 $a


echo "Font = Rotated "

figlet -f Rotated $a


echo "Font = Rounded "

figlet -f Rounded $a


echo "Font =  Rozzo "

figlet -f Rozzo $a


echo "Font =  Runyc "

figlet -f Runyc $a


echo "Font = Serifcap "

figlet -f Serifcap $a


echo "Font = Shadow "

figlet -f Shadow $a


echo "Font = Shimrod "

figlet -f Shimrod $a


echo "Font = Short "

figlet -f Short $a


echo "Font = Slant "

figlet -f Slant $a


echo "Font = Slide "

figlet -f Slide $a


echo "Font = Small Caps "

figlet -f Small Caps $a


echo "Font = Soft "

figlet -f Soft $a


echo "Font = Speed "

figlet -f Speed $a


echo "Font = Spliff "

figlet -f Spliff $a


echo "Font = Stacey "

figlet -f Stacey $a


echo "Font = Stampate "

figlet -f Stampate $a


echo "Font = Stampatello "

figlet -f Stampatello $a


echo "Font = Standard "

figlet -f Standard $a


echo "Font = Stellar "

figlet -f Stellar $a


echo "Font = Stforek "

figlet -f Stforek $a


echo "Font = Stop "

figlet -f Stop $a


echo "Font = Straight "

figlet -f Straight $a


echo "Font = Sub-Zero "

figlet -f Sub-Zero $a


echo "Font = Swan "

figlet -f Swan $a


echo "Font = Sweet "

figlet -f Sweet $a


echo "Font = THIS "

figlet -f THIS $a


echo "Font = Tanja "

figlet -f Tanja $a


echo "Font = Tengwar "

figlet -f Tengwar $a


echo "Font = Term "

figlet -f Term $a


echo "Font = Test1 "

figlet -f Test1 $a


echo "Font = Thick "

figlet -f Thick $a


echo "Font = Thin "

figlet -f Thin $a


echo "Font = Thorned "

figlet -f Thorned $a


echo "Font = Tiles "

figlet -f Tiles $a


echo "Font = Tinker-Toy "

figlet -f Tinker-Toy $a


echo "Font = Tombstone "

figlet -f Tombstone $a


echo "Font = Train "

figlet -f Train $a


echo "Font = Trek "

figlet -f Trek $a


echo "Font = Tsalagi "

figlet -f Tsalagi $a


echo "Font = Tubular "

figlet -f Tubular $a


echo "Font = Twisted "

figlet -f Twisted $a


echo "Font = Univers "

figlet -f Univers $a


echo "Font = Varsity "

figlet -f Varsity $a


echo "Font = Wavy "

figlet -f Wavy $a


echo "Font = Weird "

figlet -f Weird $a


echo "Font = Whimsy "

figlet -f Whimsy $a


echo "Font = Wow "

figlet -f Wow $a

echo " Script By < Expert Anonymous "

else
echo "Please Enter Valid Data"
fi
}


InstallingPro(){
echo "\033[1;93m[
Welcome"
figlet  "Welcome"
echo ""
apt update
apt upgrade
echo " Subscribe < Expert Anonymous YT channel For more Termux videos "
echo ""
echo " Installing FIGLET......."
apt install figlet
echo " Installing TOILET......."
apt install toilet
echo ""
echo " Installing COWSAY......."
figlet -f Bubble "installing cowsay"
apt install cowsay
echo ""
echo " Installing NODE-JS......."
figlet -f Bubble "installing NodeJs"
apt install nodejs
echo ""
echo " Installing FIGLET-cli......."
npm install figlet

figlet -f Bubble "installing figlet CLI"
npm install -g figlet-cli
echo ""
echo "\033[1;91m"

cowsay "Finished"

figlet -f small "Done!"

echo " installation Succesful [DONE!]"
echo "|-----------------------------|"
echo " Subscribe Expert Anonymous.."
echo "|-----------------------------|"
echo ""
echo "Now Run This Tool."
cd LazyFiglet
}
