#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#          Status About many Section In the Progress          #
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-Status                    #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 18-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 18-08-2022 ]                              #
###############################################################

######################################################
#------╼╼▰[ HacKingPro-Status ]--╼▰ [ Head ] #
######################################################

#------╼╼▰[ HacKingPro ]--╼▰ [ Status ]--╼▰ [ Brute Plan ]
BruteAttackStatus(){
  ToolStatus=$(echo "
    ${BCyan}${faintT}┌──${resetT}${BRed}[${DGrey} ${slowBlink}Brute Plan${resetT} ${BRed}]${faintT}${BCyan}──╼${resetT} ${BRed}[${DGrey} ⚡️ Planning and Scoping 🎯 ${BRed}]
    ${BCyan}${faintT}|
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetUserWordlist)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}WordList${BBlue}: ${BGreen}${UserWordList}
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetPassWordlist)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}PassList${BBlue}: ${BGreen}${PassWordList}
    ${BCyan}${faintT}|
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetUserName)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Username${BBlue}: ${BGreen}${UserName}
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetUserPass)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Password${BBlue}: ${BGreen}${UserPass}
    ${BCyan}${faintT}|
    ${BCyan}${faintT}└──${resetT}${BRed}[${DGrey} CL ${BRed}]${faintT}${BCyan}──╼${resetT} ${BRed}[${DGrey} 🧹 Cleaning Target Variables  🧹 ${BRed}]
    ")
    echo "$ToolStatus"
}
