#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                           Admin                             #
#-Info--------------------------------------------------------#
#    Adding Deleting Users & Groups in Linux Systems          #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-Phishing ]                #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 20-09-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 20-09-2022 ]                              #
###############################################################

#--╼▰[ Main Menu ]--╼▰ [ Phishing ]
# Phishing
# You will set up phishing infrastructure, write a convincing phishing email and try to trick your target into opening your email in a real-world simulation.

# Smishing - is phishing through SMS messages
# Vishing - is performed through phone calls



# The Senders Address:
# Ideally, the sender's address would be from a domain name that spoofs a significant brand, a known contact, or a coworker.
# See the Choosing A Phishing Domain task below for more information on this.

# To find what brands or people a victim interacts with, you can employ OSINT (Open Source Intelligence) tactics.
# For example:
# - Observe their social media account for any brands or friends they talk to.
# - Searching Google for the victim's name and rough location for any reviews the victim may have left about local businesses or brands.
# - Looking at the victim's business website to find suppliers.
# - Looking at LinkedIn to find coworkers of the victim.


# The Subject:
# You should set the subject to something quite urgent, worrying, or piques the victim's curiosity, so they do not ignore it and act on it quickly.
# Examples of this could be:
# - Your account has been compromised.
# - Your package has been dispatched/shipped.
# - Staff payroll information (do not forward!)
# - Your photos have been published.

# -> <a href="http://spoofsite.thm">Click Here</a>
# -> <a href="http://spoofsite.thm">https://onlinebank.thm</a>

# The Content:
# If impersonating a brand or supplier, it would be pertinent to research their standard email templates and branding (style, logo's images, signoffs etc.) and make your content look the same as theirs, so the victim doesn't expect anything.
# If impersonating a contact or coworker, it could be beneficial to contact them;
# first, they may have some branding in their template, have a particular email signature or even something small such as how they refer to themselves, for example, someone might have the name Dorothy and their email is dorothy@company.thm.
# Still, in their signature, it might say "Best Regards, Dot".
# Learning these somewhat small things can sometimes have quite dramatic psychological effects on the victim and convince them more to open and act on the email.

# A certain amount of infrastructure will need to be put in place to launch a successful phishing campaign.

echo "
[##] Phishing Infrastructure
[01] Domain Name:
[02] SSL/TLS Certificates:
[03] Email Server/Account:
[04] DNS Records:
[05] Web Server:
[06] Analytics:
"

# Domain Name:
# You'll need to register either an authentic-looking domain name or one that mimics the identity of another domain.
# See task 5 for details on how to create the perfect domain name.

# SSL/TLS Certificates:
# Creating SSL/TLS certificates for your chosen domain name will add an extra layer of authenticity to the attack.

# Email Server/Account:
# You'll need to either set up an email server or register with an SMTP email provider.

# DNS Records:
# Setting up DNS Records such as SPF, DKIM, DMARC will improve the deliverability of your emails and make sure they're getting into the inbox rather than the spam folder.

# Web Server:
# You'll need to set up webservers or purchase web hosting from a company to host your phishing websites.
# Adding SSL/TLS to the websites will give them an extra layer of authenticity.

# Analytics:
# When a phishing campaign is part of a red team engagement, keeping analytics information is more important.
# You'll need something to keep track of the emails that have been sent, opened or clicked.
# You'll also need to combine it with information from your phishing websites for which users have supplied personal information or downloaded software.

# Automation And Useful Software:
# Some of the above infrastructures can be quickly automated by using the below tools.

# GoPhish - (Open-Source Phishing Framework) - https://getgophish.com
# GoPhish is a web-based framework to make setting up phishing campaigns more straightforward.
# GoPhish allows you to store your SMTP server settings for sending emails, has a web-based tool for creating email templates using a simple WYSIWYG (What You See Is What You Get) editor.
# You can also schedule when emails are sent and have an analytics dashboard that shows how many emails have been sent, opened or clicked.

# SET - (Social Engineering Toolkit) - trustedsec.com
# The Social Engineering Toolkit contains a multitude of tools, but some of the important ones for phishing are the ability to create spear-phishing attacks and deploy fake versions of common websites to trick victims into entering their credentials.
