#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                           TargetPro                         #
#-Info--------------------------------------------------------#
#             Target:  Hints | Checklist | Todo |             #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-TargetPro ]               #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 17-10-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 17-10-2022 ]                              #
###############################################################

#--╼▰[ Main Menu ]--╼▰ [ TargetPro]
####### Table of contents
# File permissions.

echo "


- OS:
- User:
- User's:
- Version:
- Browser:
- Hotfixes:
- Host Name:
- Net Users:
- Antivirus:
- Local Groups:
- Architecture:
- Weak Passwords:
- Kernel Exploits:
- Inside Services:
- Scheduled Tasks:
- Interesting Files:
- Installed Software:
- Cleartext Password:
- Passwords and Hashes:
- Program Running as root:
- Reconfigure Services Parameters:


"
