#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                           AttacKing                         #
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-AttacKing ]               #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 20-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 20-08-2022 ]                              #
###############################################################

#--╼▰[ Main Menu ]--╼▰ [ 04 ]--╼▰ [ AttacKing ]
MainAttacKing(){
  AttacKing=$(echo "${BRed}Atta${BYellow}King")
  while true; do
    clear
    ToolHeaderRun
    TargetStatusRun
    BruteAttackStatus
    AttacKingMenuMain="$(echo "
    ${BYellow}${faintT}┌──╼ ${resetT}${BRed}[${BYellow} ${AttacKing} ${BRed}]
    ${BYellow}${faintT}|
    ${BYellow}${faintT}|  ┏━╼▰[ (01) ]╼▰ [ Malware ]
    ${BYellow}${faintT}|  ┣━╼▰[ (02) ]╼▰ [ Phishing ]
    ${BYellow}${faintT}|  ┣━╼▰[ (03) ]╼▰ [ Password ]
    ${BYellow}${faintT}|  ┣━╼▰[ (04) ]╼▰ [ (DOS) ]━╼▰ [ Denial-of-Service ]
    ${BYellow}${faintT}|  ┣━╼▰[ (05) ]╼▰ [ (XSS) ]━╼▰ [ Cross-site scripting ]
    ${BYellow}${faintT}|  ┣━╼▰[ (06) ]╼▰ [ (MITM) ]╼▰ [ Man-in-the-Middle ]
    ${BYellow}${faintT}|  ┣━╼▰[ (07) ]╼▰ [ (SQLI) ]╼▰ [ SQL Injection ]
    ${BYellow}${faintT}|  ┗━╼▰[ (08) ]╼▰ [  ]
    ${BYellow}${faintT}|
    ${BYellow}${faintT}|
    ${BYellow}${faintT}└──╼${resetT}${BRed}[${DGrey} X ${BRed}]${BYellow}${faintT}──╼ ${resetT}${BRed}[${DGrey} Exit / Quit / Close ${BRed}]

    ${BGreen}┌──${BRed}[${ORANGE} Arsenal ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BGreen} $ArsenalCommand ${BRed}]${BGreen}${resetT}
    ${BGreen}|
    ${BGreen}|──${BRed}[${DGrey} ~$(pwd) ${BRed}]
    ${BGreen}|
    ${BGreen}└──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} 🔮 ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BGreen}   ")"

    read -p "$AttacKingMenuMain" cmd
    case $cmd in
      "?"|help|about|About )
      about
      Press_ENTER
      ;;
      * )
      echo "$InvalidOption"
      ;;
    esac
  done
}
