#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                           ProfilePro                        #
#-Info--------------------------------------------------------#
#    Adding Deleting Users & Groups in Linux Systems          #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-ProfilePro ]              #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 14-10-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 14-10-2022 ]                              #
###############################################################

#--╼▰[ Main Menu ]--╼▰ [ ProfilePro ]
####### Table of contents
# File permissions.
# Number	Permission
# 0	No permission

Basic_Information(){
  echo "
    # Basic Information
      - Name:
      - Course:
      - Religion:
      - Nickname:
      - Ethnicity:
      - Star Sign:
      - Sexuality:
      - Education:
      - Nationality:
      - Career Paths:
      - Social Class:
      - Date of Birth:
      - Political Views:
      - Reason for Nickname:
      - Relationship Status:
    "

}

Physical_Characteristics(){
  echo "
    # Physical characteristics
      - Height:
      - Shape:
      - Build:
      - Eyes:
      - Face Shape:
      - Hair Color:
      - Glasses/Lenses:
      - Distinguishing marks:
      - Prosthetics	prosthetic leg
      - Other words that might be used:
      - Reason for prosthetic	he lost his in a car accident
      - Due to the the internet, Mark looks older than his actual age.
  "

}
