#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                       Linux                                 #
#-Info--------------------------------------------------------#
#                                                             #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-Linux ]                   #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 0.0.12 ]                                 #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 02-10-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 03-10-2022 ]                              #
###############################################################
#--╼▰[ Main Menu ]--╼▰ [ Linux ]
while true; do
  clear
  ToolHeaderRun
  TargetStatusRun
  echo "
  ┏────╼ ${BRed}[${BYellow} Command and Control ${BRed}]
  ┖─┲──╼ ${BRed}[${BYellow} The intruder gains persistent access to the victim’s systems/network ${BRed}]
    ┖──╼ ${BRed}[${BYellow} Malware enables intruder to have hands on the keyboard persistent access to target network. ${BRed}]

  ${DGrey}┏--${BRed}[${BGreen} 01 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lsusb ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} List USB Devices ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 02 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lsblk ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} List Block Devices ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 03 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lspci ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} List all PCI Devices ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 04 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lslocks ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} List local system locks ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 05 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lsdiff ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} show which files are modified by a patch ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 06 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}dmesg ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} Print or Control the Kernel Ring Buffer ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 07 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lscpu ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} Display Information about the CPU Architecture ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 08 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lsmod ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} Show the Status of Modules in the Linux Kernel ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 09 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lslogins ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} Display Information About known Users in the System ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 10 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lsmem ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} List the Ranges of available Memory with their online Status ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 11 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lsipc ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} Show Information on IPC Facilities Currently Employed in the System ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 12 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lstopo ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} lstopo-no-graphics, hwloc-ls - Show the topology of the system ${BRed}]
  ${DGrey}┃--${BRed}[${BGreen} 12 ${BRed}]${BGreen}-╼▰ ${BRed}[ ${ORANGE}lstopo ${BRed}]${BGreen}--╼▰ ${BRed}[${LGrey} lstopo-no-graphics, hwloc-ls - Show the topology of the system ${BRed}]
  ${DGrey}┗--${BRed}[${DGrey} XX ${BRed}]${BGreen}-╼▰ ${BRed}[${DGrey} Exit / Quit / Close ${BRed}]

   ${DGrey}┏--[ ## ]-╼▰ [ Services ]--╼▰ [ List Services ]
   ${DGrey}┃--[ 13 ]-╼▰ [ service --status-all ]--╼▰ [ List All Services ]
   ${DGrey}┃--[ 14 ]-╼▰ [ service --status-all | grep + ]--╼▰ [ List All Services That UP and Running ]


  "
  CMD_PROMPT="$(
  echo "
  ${BGreen}┏──${BRed}[${DGrey} ~$(pwd) ${BRed}]
  ${BGreen}|
  ${BGreen}┗──${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BYellow}╼▰  ${BRed}[${BGreen} Linux ${BRed}]${BYellow}╼▰  ${BGreen}   ")"
  read -p "${CMD_PROMPT}" cmd
  case $cmd in
    01 ) lsusb;read cc ;; # ]--╼▰ [ List USB Devices ]
    02 ) lsblk;read cc ;; # ]--╼▰ [ List Block Devices ]
    03 ) lspci;read cc ;; # ]--╼▰ [ List all PCI Devices ]
    04 ) lslocks;read cc ;; # ]--╼▰ List local system locks ]
    05 ) lsdiff;read cc ;; # ]--╼▰ show which files are modified by a patch ]
    06 ) dmesg;read cc ;; # ]--╼▰ [ Print or Control the Kernel Ring Buffer ]
    07 ) lscpu;read cc ;; # ]--╼▰ [ Display Information about the CPU Architecture ]
    08 ) lsmod;read cc ;; # ]--╼▰ [ Show the Status of Modules in the Linux Kernel ]
    09 ) lslogins;read cc ;; # ]--╼▰ [ Display Information About known Users in the System ]
    10 ) lsmem;read cc ;; # ]--╼▰ [ List the Ranges of available Memory with their online Status ]
    11 ) lsipc;read cc ;; # ]--╼▰ [ Show Information on IPC Facilities Currently Employed in the System ]
    12 ) lstopo;read cc ;; # ]--╼▰ lstopo-no-graphics, hwloc-ls - Show the topology of the system
  esac
done
