#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                           AttacKing                         #
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-Enumeration ]             #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
# tnx to https://tryhackme.com/room/enumerationpe

#--╼▰[ Main Menu ]--╼▰ [ 04 ]--╼▰ [ Enumeration ]--╼▰ [ Linux ]
LinuxEnumerationPro(){
  while true; do
    clear
    ToolHeaderRun
    TargetStatusRun
    EnumerationProMenuMain=$(echo "${BRed}
    ${ORANGE}┏━╼ ${BRed}[${LGreen} Linux System Enumeration ${BRed}]
    ${ORANGE}┖─┲━╼ ${BRed}[${BGreen} Users ${BRed}]${LGreen}─${resetT}${BYellow}╼▰
    ${ORANGE}  ┣━╼ ${BRed}[${BGreen} System ${BRed}]${LGreen}─${resetT}${BYellow}──╼▰
    ${ORANGE}  ┣━╼ ${BRed}[${BGreen} NetWorKing ${BRed}]${LGreen}─${resetT}${BYellow}──╼▰
    ${ORANGE}  ┖━╼ ${BRed}[${BGreen} Running Services ${BRed}]${LGreen}─${resetT}${BYellow}──╼▰

    ${BGreen}┏━╼▰ ${BRed}[${ORANGE} Arsenal ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BGreen} $ArsenalCommand ${BRed}]${BGreen}${resetT}
    ${BGreen}┃
    ${BGreen}┣━╼▰ ${BRed}[${DGrey} ~$(pwd) ${BRed}]━╼▰ ${BRed}[${DGrey} $(date) ${BRed}]
    ${BGreen}┃
    ${BGreen}┗━╼▰ ${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} Enumeration ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} Linux ${BRed}]${BGreen}──${resetT}${BYellow}╼▰${BGreen}   ")
    read -p "$EnumerationProMenuMain" cmd
    case $cmd in
      # [ Users ] - [ 3 ] Commands Exported
      "users"|"Users" )
      echo "# Users Enumeration " >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "---" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md

      # Showing Who is Logged
      echo "## Who is Logged" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "\`\`\`" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      who >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "\`\`\`" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md

      # Showing Who is Current Users
      echo "## Who is Current Users" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "\`\`\`" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      whoami >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "\`\`\`" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md

      # Showing User & Group ID of Current User
      echo "## User & Group ID of Current User" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "\`\`\`" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      id  >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "\`\`\`" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md

      echo "---" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      # Open Created Log
      less -R ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      Press_ENTER
       ;;
      # [ Systems ] - [ 8 ] Commands Exported
      "systems"|"Systems" )
      echo "# Systems Enumeration " >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "---" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      # Linux Distribution and Release Version
      echo "Linux Distribution and Release Version" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      ls /etc/*-release
      # Linux System Host Name
      echo "Linux System Host Name" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      hostname
      # Linux System Users
      echo "Linux System Users" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      cat /etc/passwd
      # Linux System Groups
      echo "Linux System Groups" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      cat /etc/group
      #  Linux System Hashed Passwords | Requires root Privileges
      echo "Linux System Hashed Passwords" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      cat /etc/shadow
      #  Linux System Emails
      echo "Linux System Emails" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      ls -lh /var/mail/
      #  Linux System Binary
      echo "Linux System Applications / Binary" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "/usr/bin/" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      ls -lh /usr/bin/
      echo "/sbin/" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      ls -lh /sbin/
      Press_ENTER
      ;;
      # [ NetWorKing ] - [ 0 ] Commands Exported
      "networking"|"NetWorKing" )
      echo "# NetWorKing Enumeration " >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "---" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      Press_ENTER

      ;;
      # [ Running Services ] - [ 0 ] Commands Exported
      "running services"|"Running Services" )
      echo "# Running Services Enumeration " >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      echo "---" >> ${MainDirectoriyCaseNameEnumeration}/${targetNAME}-HacKingPro-Enumeration-Log.md
      Press_ENTER
      ;;


      x|X|exit|quit|Exit )
      clear
      cd ${MainDirectoriy}
      AwesomeLineExit
      break
      ;;
      esac
  done

}
#--╼▰[ Main Menu ]--╼▰ [ 04 ]--╼▰ [ Enumeration ]--╼▰ [ Windows ]
WindowsEnumerationPro(){
  while true; do
    clear
    ToolHeaderRun
    TargetStatusRun
    EnumerationProMenuMain=$(echo "${BRed}
    ${ORANGE}┏━╼ ${BRed}[${LGreen} Windows System Enumeration ${BRed}]
    ${ORANGE}┖─┲━╼ ${BRed}[${BGreen} Users ${BRed}]${LGreen}─${resetT}${BYellow}╼▰
    ${ORANGE}  ┣━╼ ${BRed}[${BGreen} System ${BRed}]${LGreen}─${resetT}${BYellow}──╼▰
    ${ORANGE}  ┣━╼ ${BRed}[${BGreen} NetWorKing ${BRed}]${LGreen}─${resetT}${BYellow}──╼▰
    ${ORANGE}  ┖━╼ ${BRed}[${BGreen} Running Services ${BRed}]${LGreen}─${resetT}${BYellow}──╼▰

    ${BGreen}┏━╼▰ ${BRed}[${ORANGE} Arsenal ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BGreen} $ArsenalCommand ${BRed}]${BGreen}${resetT}
    ${BGreen}┃
    ${BGreen}┣━╼▰ ${BRed}[${DGrey} ~$(pwd) ${BRed}]━╼▰ ${BRed}[${DGrey} $(date) ${BRed}]
    ${BGreen}┃
    ${BGreen}┗━╼▰ ${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} Enumeration ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} Windows ${BRed}]${BGreen}──${resetT}${BYellow}╼▰${BGreen}   ")
    read -p "$EnumerationProMenuMain" cmd
    case $cmd in
      "users"|"Users" )
      Press_ENTER
      ;;
      "systems"|"Systems" )
      Press_ENTER
      ;;
      "networking"|"NetWorKing" )
      Press_ENTER
      ;;
      "running services"|"Running Services" )
      Press_ENTER
      ;;
      x|X|exit|quit|Exit )
      clear
      cd ${MainDirectoriy}
      AwesomeLineExit
      break
      ;;
      esac
    done
}
#--╼▰[ Main Menu ]--╼▰ [ 04 ]--╼▰ [ Enumeration ]
EnumerationPro() {
  while true; do
    clear
    ToolHeaderRun
    TargetStatusRun
    EnumerationProMenuMain=$(echo "${BRed}
    ${BGreen}${faintT}┏━━━━╼${resetT} ${BRed}[${LCyan} Systems Enumeration ${BRed}]
    ${BGreen}${faintT}┗━┲━━╼${resetT} ${BRed}[${BCyan}${faintT} The Purpose is to Collect Information About the System to Gaining more Access ${resetT}${BRed}]
    ${BGreen}${faintT}  ┗━┲━━╼${resetT} ${BRed}[${LGrey}${faintT} Some of the information we are interested in gathering include: ${resetT}${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Users and groups ${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Hostnames ${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Routing tables ${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Network shares ${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Network services ${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Applications and banners ${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Firewall configurations ${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Service settings and audit configurations ${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} SNMP and DNS details ${BRed}]
    ${BGreen}${faintT}    ┖━━╼${resetT} ${BRed}[${DGrey} Hunting for credentials (saved on web browsers or client applications) ${BRed}]

    ${LGreen}┏━╼▰ ${BRed}[${LGreen} Linux System Enumeration ${BRed}]
    ${LGreen}┗━╼▰ ${BRed}[${LGreen} Windows System Enumeration ${BRed}]


    ${BGreen}┏━╼▰ ${BRed}[${ORANGE} Arsenal ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BGreen} $ArsenalCommand ${BRed}]${BGreen}${resetT}
    ${BGreen}┃
    ${BGreen}┣━╼▰ ${BRed}[${DGrey} ~$(pwd) ${BRed}]━╼▰ ${BRed}[${DGrey} $(date) ${BRed}]
    ${BGreen}┃
    ${BGreen}┗━╼▰ ${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} Enumeration ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BGreen}   ")
    read -p "$EnumerationProMenuMain" cmd
  case $cmd in
    "lin"|"linux"|"Linux" )
    LinuxEnumerationPro
    Press_ENTER
    ;;
    "win"|"windows"|"Windows" )
    WindowsEnumerationPro
    Press_ENTER
    ;;
    x|X|exit|quit|Exit )
    clear
    cd ${MainDirectoriy}
    AwesomeLineExit
    break
    ;;
    esac
done
}


#--╼▰[ Version ]-╼▰[ 0.1.5.11 ]
#                    ┣━╋━╋━┫
#                    ┃ ┃ ┃ ┃
#                    ┃ ┃ ┃ ┖━ Optional to Use & Exported Enumeration Commands
#                    ┃ ┃ ┖━━━ Enumeration Systems Categories
#                    ┃ ┖━━━━━ Enumeration Systems Support
#                    ┖━━━━━━━ Finish Main Goal
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 0.1.5.11 ]                               #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 20-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 20-08-2022 ]                              #
###############################################################
