#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#                     Local Server Pro                        #
#-Info--------------------------------------------------------#
#    Start Local Server                                       #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-LocalServer ]             #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 0.0.1 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 30-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 17-09-2022 ]                              #
###############################################################
# tnx to https://tryhackme.com/room/enumerationpe

# If Python version returned above is 3.X
# On Windows, try "python -m http.server" or "py -3 -m http.server"
# python3 -m http.server
# If Python version returned above is 2.X
# python -m SimpleHTTPServer

ip=$(ifconfig tun0 | grep inet | grep -v inet6 | awk '{print $2}')
#--╼▰[ Main Menu ]--╼▰ [ 02 ]--╼▰ [ LocalServerPro ]
LocalServerPro() {
  while true; do
    clear
    ToolHeaderRun
    TargetStatusRun
    EnumerationProMenuMain=$(echo "${BRed}
    ${BGreen}${faintT}┏━━━━╼${resetT} ${BRed}[${LCyan} Local Server Pro ${BRed}]
    ${BGreen}${faintT}┗━┲━━╼${resetT} ${BRed}[${BCyan}${faintT} The Purpose is to Create Local Server in the System to Give Access ${resetT}${BRed}]
    ${BGreen}${faintT}  ┗━┲━━╼${resetT} ${BRed}[${LGrey}${faintT} Some of the Access we are Giving in Local Server: ${resetT}${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Files Sharing ${BRed}]
    ${BGreen}${faintT}    ┣━━╼${resetT} ${BRed}[${DGrey} Web Sites ${BRed}]
    ${BGreen}${faintT}    ┖━━╼${resetT} ${BRed}[${BYellow} Hunting for Credentials (Saved on Web Browsers or Client Applications) ${BRed}]

    ${LGreen}┏━╼▰ ${BRed}[${LGreen} Linux System Server ${BRed}]
    ${LGreen}┣━╼▰ ${BRed}[${LGreen} Windows System Server ${BRed}]
    ${LGreen}┣━╼▰ ${BRed}[${LGreen} Android System Server ${BRed}]
    ${LGreen}┗━╼▰ ${BRed}[${LGreen} MacOS System Server ${BRed}]

    ${BGreen}┏━╼▰ ${BRed}[${ORANGE} Arsenal ${BRed}]${BGreen}──${resetT}${BYellow}╼▰  ${BRed}[${BGreen} $ArsenalCommand ${BRed}]${BGreen}${resetT}
    ${BGreen}┃
    ${BGreen}┣━╼▰ ${BRed}[${DGrey} ~$(pwd) ${BRed}]━╼▰ ${BRed}[${DGrey} $(date) ${BRed}]
    ${BGreen}┃
    ${BGreen}┗━╼▰ ${BRed}[${BYellow} $(AnLoMinus) ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BRed}[${BGreen} LocalServerPro ${BRed}]${BGreen}──${resetT}${BYellow}╼▰ ${BGreen}   ")
    read -p "$EnumerationProMenuMain" cmd
  case $cmd in
    "lin"|"linux"|"Linux" )
    Press_ENTER
    ;;
    "win"|"windows"|"Windows" )
    Press_ENTER
    ;;
    "macos"|"MacOS" )
    Press_ENTER
    ;;
    "arm"|"android"|"Android" )
    Press_ENTER
    ;;
    x|X|exit|quit|Exit )
    clear
    cd ${MainDirectoriy}
    AwesomeLineExit
    break
    ;;
    esac
done
}
