#!/bin/sh
#!/bin/bash
#!/usr/bin/sh
#!/usr/bin/bash
#!/usr/bin/env sh
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/sh
#!/data/data/com.termux/files/usr/bin/bash
###############################################################
#-Info--------------------------------------------------------#
#    Enter Your Target, Hack Him, and Get Markdown Report     #
#-About-------------------------------------------------------#
#--╼▰[ Skils ]-╼▰[ MultiMan ]                                 #
#--╼▰[ Part of ]-╼▰[ HacKingPro ]                             #
#--╼▰[ Script Name ]-╼▰[ HacKingPro-LazyRecon ]                #
#--╼▰[ Author ]-╼▰[ AnLoMinus ]-╼▰[ Leon Yaakobov ]           #
###############################################################
# CREDIT: To All World Creators free Scripts & Tools          #
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE          #
# GREAT SCRIPTS                                               #
# Location: Made With LOVE IN ISRAEL !                        #
###############################################################
#-Metadata----------------------------------------------------#
#--╼▰[ Version ]-╼▰[ 1.0.0 ]                                  #
#--╼▰[ Source ]-╼▰[ https://github.com/AnLoMinus/HacKingPro ] #
#--╼▰[ Created ]-╼▰[ 17-08-2022 ]                             #
#--╼▰[ Update ]-╼▰[ 17-08-2022 ]                              #
###############################################################
. HacKingPro-Colors
TARGET=$1
WORKING_DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
TOOLS_PATH="$WORKING_DIR/Tools"
WORDLIST_PATH="$WORKING_DIR/Wordlists"
RESULTS_PATH="$WORKING_DIR/Results/$TARGET"
CORS_PATH="$RESULTS_PATH/cors"
DIR_PATH="$RESULTS_PATH/Directory"
IP_PATH="$RESULTS_PATH/IP"
PSCAN_PATH="$RESULTS_PATH/PortScan"
SSHOT_PATH="$RESULTS_PATH/ScreenShot"
SUB_PATH="$RESULTS_PATH/SubDomain"

echo "${BGreen}--==[ Setting things up ]==--${RESET}"
echo "${BRed}[+] Creating results directories...${RESET}"
rm -rf "$RESULTS_PATH"
mkdir -p "$SUB_PATH" "$CORS_PATH" "$IP_PATH" "$PSCAN_PATH" "$SSHOT_PATH" "$DIR_PATH"

echo "
    ${BGreen}[*] ${ORANGE}$SUB_PATH${resetT}
    ${BGreen}[*] ${ORANGE}$CORS_PATH${resetT}
    ${BGreen}[*] ${ORANGE}$IP_PATH${resetT}
    ${BGreen}[*] ${ORANGE}$PSCAN_PATH${resetT}
    ${BGreen}[*] ${ORANGE}$SSHOT_PATH${resetT}
    ${BGreen}[*] ${ORANGE}$DIR_PATH${resetT}
    ${BGreen}[*] ${ORANGE}$TOOLS_PATH${resetT}
    ${BGreen}[*] ${ORANGE}$WORDLIST_PATH${resetT}
"
