#!/bin/bash

# Written : Edo maland
#     - mail : screetsec@dracos-linux.org

imR0T_NAME="imR0T"
imR0T_VERSION="1.0 ~ beta"
     
[[ `id -u` -eq 0 ]] || { echo "You Must Get root acess to run this tool "; exit 1; }


source src/_general_functions
source src/_im_R0T_enc_functions
source src/_im_R0T_dec_functions
     
controller () {
 clear;imr0t_colour;banner_
   	while /bin/true
    	do
		echo -ne $okegreen"\nimR0T"$white"╺─╸"$okegreen"[ "$white"cli"$okegreen" ]"$red" > ";tput sgr0 ;read cnt_1 cnt_2 cnt_3
		#arguments
	     	if   [[ $cnt_1 == "help" ]];then
	     		imr0t_help
	     	elif [[ $cnt_1 == "pwd" ]];then
	     		echo;pwd
	     	elif [[ $cnt_1 == "clear" ]];then
	     		clear
	     	elif [[ $cnt_1 == "set" ]];then
	     		err 
	     	elif [[ $cnt_1 == "run" ]];then
	     		err 
	     	elif [[ $cnt_1 == "options" ]];then
	     		err      		     							     							     							  								     													
	     	elif [[ $cnt_1 == "show" ]] ;then
	     		fu_un_module
	     	elif [[ $cnt_1 == "ls" ]] || [[ $cnt_1 == "dir" ]];then
	     		echo -e $red"";ls 							
	     	elif [[ $cnt_1 == "cat" ]] && [[ $cnt_2 == $cnt_2 ]];then
	     		echo;cat $cnt_2      							
	     	elif [[ $cnt_1 == "use" ]] && [[ $cnt_2 == "0x1" ]];then
	     		encryption
	     	elif [[ $cnt_1 == "use" ]] && [[ $cnt_2 == "0x2" ]];then
	     		decryption 						
	     	elif [[ $cnt_1 == "use" ]];then #not spesific
	     		err1     
	     	elif [[ $cnt_1 == "list" ]] && [[ $cnt_2 == "style" ]];then
	     		err   	
	     	elif [[ $cnt_1 == "exit" ]];then 
	     		exit    	     		
	     	else
	     		oops
	   fi
	  done
}	
     
     controller
