#!/bin/bash

case_sen="tmp/case_sensitive.tmp"
#out_enc
msg_enc1="tmp/enc1.tmp";msg_enc2="tmp/enc2.tmp";msg_enc3="tmp/enc3.tmp";msg_enc4="tmp/enc4.tmp"
#out_dec
msg_dec1="tmp/dec1.tmp";msg_dec2="tmp/dec2.tmp";msg_dec3="tmp/dec3.tmp";msg_dec4="tmp/dec4.tmp";msg_fin="tmp/msg_fin";tmp_check="tmp/out.send"


encryption(){
 clear;#imr0t_colour;#banner_
   	while /bin/true
    	do
		echo -ne $okegreen"\nimR0T╺─╸[ "$white"enc"$okegreen" ] "$red"> " $RESET;read case1 case2 case3
		#arguments
	     	if   [[ $case1 == "help" ]];then
	     		imr0t_help
	     	elif [[ $case1 == "pwd" ]];then
	     		echo;pwd
	     	elif [[ $case1 == "clear" ]];then
	     		clear
	     	elif [[ $case1 == "list" ]] && [[ $case2 == "style" ]];then
	     		echo -e "\n | "
				echo " | "
				echo " |_ "
				echo "    style:"
				echo ""
				echo -e $okegreen "\t  [1] "$RESET"Cat Face \t\t  "$okegreen"[10] "$RESET"Chess\t\t "$okegreen"[19] "$RESET"Fraction"	   
				echo -e $okegreen "\t  [2] "$RESET"Emoji \t\t  "$okegreen"[11] "$RESET"Degree\t\t "$okegreen"[20] "$RESET"Technical"
				echo -e $okegreen "\t  [3] "$RESET"Cards \t\t  "$okegreen"[12] "$RESET"Astrological\t "$okegreen"[21] "$RESET"Square"	   
				echo -e $okegreen "\t  [4] "$RESET"Fake Hex \t\t  "$okegreen"[13] "$RESET"Heart\t\t "$okegreen"[22] "$RESET"Triangle"	
				echo -e $okegreen "\t  [5] "$RESET"Stars \t\t  "$okegreen"[14] "$RESET"Check mark\t "$okegreen"[23] "$RESET"Phonetic"
				echo -e $okegreen "\t  [6] "$RESET"Hand sign\t\t  "$okegreen"[15] "$RESET"Greek"	
				echo -e $okegreen "\t  [7] "$RESET"Weather \t\t  "$okegreen"[16] "$RESET"Greekv2"	
				echo -e $okegreen "\t  [8] "$RESET"Music note\t  "$okegreen"[17] "$RESET"Math"
				echo -e $okegreen "\t  [9] "$RESET"Arrow \t\t  "$okegreen"[18] "$RESET"Number japan"
				echo -e ""
	     	elif [[ $case1 == "options" ]];then
	     		echo -e "\n | "
				echo " | "
				echo " |_ "
				echo "    Options:"
				echo ""
				echo -e $okegreen"	     name      example             value"   
				echo -e $okegreen"	     -----     -----------------   -----"
				echo -e $okegreen"	     file      "$RESET"/root/message.txt   $file"
				echo -e $okegreen"	     style     "$RESET"template/0x1.key    $type"
				echo ""   
			elif [[ $case1 == "set" ]];then
				if [[ $case2 == "file" ]] && [[ ! $case3 == "" ]]
					then
						file=$case3
				elif [[ $case2 == "style" ]] && [[ ! $case3 == "" ]]
				then
					if [[ $case3 == "1" ]];then
			          type1=template/0x1.key
			          type=$type1 
			        elif [[ $case3 = "2" ]]; then
			          type1=template/0x2.key
			          type=$type1 
			        elif [[ $case3 = "3" ]]; then
			          type1=template/0x3.key
			          type=$type1
			        elif [[ $case3 = "4" ]]; then
			          type1=template/0x4.key
			          type=$type1 
			        elif [[ $case3 = "5" ]]; then
			          type1=template/0x5.key
			          type=$type1 
			        elif [[ $case3 = "6" ]]; then
			          type1=template/0x6.key
			          type=$type1 
			        elif [[ $case3 = "7" ]]; then
			          type1=template/0x7.key
			          type=$type1 
			        elif [[ $case3 = "8" ]]; then
			          type1=template/0x8.key
			          type=$type1
			        elif [[ $case3 = "9" ]]; then
			          type1=template/0x9.key
			          type=$type1 
			        elif [[ $case3 = "10" ]]; then
			          type1=template/0x10.key
			          type=$type1 
			        elif [[ $case3 = "11" ]]; then
			          type1=template/0x11.key
			          type=$type1 
			        elif [[ $case3 = "12" ]]; then
			          type1=template/0x12.key
			          type=$type1 
			        elif [[ $case3 = "13" ]]; then
			          type1=template/0x13.key
			          type=$type1
			        elif [[ $case3 = "14" ]]; then
			          type1=template/0x14.key
			          type=$type1 
			        elif [[ $case3 = "15" ]]; then
			          type1=template/0x15.key
			          type=$type1 
			        elif [[ $case3 = "16" ]]; then
			          type1=template/0x16.key
			          type=$type1 
			        elif [[ $case3 = "17" ]]; then
			          type1=template/0x17.key
			          type=$type1 
			        elif [[ $case3 = "18" ]]; then
			          type1=template/0x18.key
			          type=$type1
			        elif [[ $case3 = "19" ]]; then
			          type1=template/0x19.key
			          type=$type1 
			        elif [[ $case3 = "20" ]]; then
			          type1=template/0x20.key
			          type=$type1 
			        elif [[ $case3 = "21" ]]; then
			          type1=template/0x21.key
			          type=$type1 			          			          
			        elif [[ $case3 = "22" ]]; then
			          type1=template/0x22.key
			          type=$type1 			          			          
			        elif [[ $case3 = "23" ]]; then
			          type1=template/0x23.key
			          type=$type1 			          			          
			          			          			          

			       fi 
				fi

	     	elif [[ $case1 == "ls" ]] || [[ $case1 == "dir" ]];then
	     		echo -e $red"";ls 								
	     	elif [[ $case1 == "cat" ]] && [[ $case2 == $case2 ]];then
	     		echo;cat $case2      							 						
	     	elif [[ $case1 == "use" ]];then #not spesific
	     		err1  
	     	elif [[ $case1 == "back" ]];then
	     		controller    
	     	elif [[ $case1 == "run" ]];then #not spesific
			    key=13
					if [ -f "$file" ]
						then
						#clear 
						echo -e "\n | "
						echo " |_ "
						echo -e $okegreen"    [+] "$RESET"Process Case Senstive \n"
						awk '{print tolower($0)}' < $file > $case_sen
					    echo -e $okegreen"    [+] "$RESET"Process Encryption ROT13 \n"
					    export A=$(echo {a..z} | sed -r 's/ //g')
					    export B=$(echo $A | sed -r "s/^.{$key}//g")$(echo $A | sed -r "s/.{$( expr 26 - $key )}$//g")
					    tr '[A-Z]' $A < $case_sen | tr $A $B > $msg_enc1
					    echo -e $okegreen"    [+] "$RESET"Exec Multi Encryption\n"
						value0x1=$(<$msg_enc1);echo $value0x1 | awk '{print toupper($0)}' | tr -d "\n" | od -An -t uC  | tr -d '\040\011\012\015' | tr 0123456789 ABCDEFGHIJ > $msg_enc2
						echo -e $yellow"         [-]"$RESET" Process "$okegreen0"0x1"
						value0x2=$(<$msg_enc2);echo $value0x2 | od -A n -t x1 |sed 's/ /\ /g'|  tr -d '\040\011\012\015'  | tr 0123456789 ABCDEFGHIJ > $msg_enc3
						echo -e $yellow"         [-]"$RESET" Process "$okegreen0"0x2"
						tr '[N-ZA-M]' '[A-Z]' < $msg_enc3 > $msg_enc4 
						echo -e $yellow"         [-]"$RESET" Process "$okegreen0"0x3"
						value0x3=$(<$msg_enc4);	#for subs in $(echo $value0x3) ; #do echo $subs; 
						echo -e $yellow"         [-]"$RESET" Process "$okegreen0"0x4";
						while IFS=" - " read x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 ; do
						sed -e 's/N/'$x1'/g' -e 's/O/'$x2'/g' -e 's/P/'$x3'/g' -e 's/Q/'$x4'/g' -e 's/R/'$x5'/g' -e 's/S/'$x6'/g' -e 's/T/'$x7'/g' -e 's/U/'$x8'/g' -e 's/V/'$x9'/g' -e 's/W/'$x10'/g' -e 's/a/'$x11'/g' < $msg_enc4  > output/Smile.imR0T
						done < $type1
						echo;echo -e $okegreen"    [+]"$RESET" Process Complete \n $RESET"
						echo -ne $okegreen" Send this encryption message into whatsapp without save the number( Y/N ): $RESET" 
						read back
						       if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'no' ] && [ $back != 'No' ]
       					then
       					source conf/whatsapp.conf
       					echo -e "\n | "
						echo " |_ "
						echo -ne $okegreen"    [+] "$RESET"Enter the number with country code ( Ex:628xx):  "
						read Phone
						Message_0K=`cat output/Smile.imR0T`
						echo ""
					 	echo -e $yellow"         [-]"$RESET"Process send a message $RESET";curl -s --request GET --url "https://panel.apiwha.com/send_message.php?apikey=$api&number=$Phone&text=$Message_0K"  > $tmp_check
					 	check_1=$(cat $tmp_check | grep false)
						 	if [ $? -ne 0 ];then
 								echo -e $yellow"\n         [-]"$RESET"Message success send to $Phone"
							else
								echo -e $yellow"\n         [-]"$RESET"Message Sending failed, check  your APIKEY"
							fi

       							elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'yes' ] && [ $back != 'Yes' ]
       					then
       					echo ""
							fi
						#clear tmp
						rm -rf tmp/*
						#rm -rf tmp/*.send;rm -rf tmp/*.tmp; tmp -rf msg_fin 
						#value0x4=$(<tmp/Smile.imR0T)
						#OK=`cat tmp/Smile.imR0T`
					 	#$OK
					 	#sed s/PESANRAHASIA/$OK/g send.html > whatsapp.html
						#firefox whatsapp.html
						#rm -rf tmp/*.tmp


						elif [ ! -f "$file" ] 
							then
	     					echo -e "\n | "
							echo " |_ "
							echo -e $red"    [-]$RESET Error: File not found - "$okegreen"[help] $RESET"
							echo -e $red"    [-]$RESET set values to requirements before run "$okegreen"[options] $RESET"						

						fi	
						

	     	else
	     		oops
	   fi
	  done
}	

