#!/bin/sh
# Name : CoreMan
# Date : April 2022
# Description : CoreMan is a CoreMan tools installer and package manager for hacker's.
# |
nc="\033[00m"
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[32m"
yellow="\033[33m"
purple="\033[0;35m"
cyan="\033[1;36m"
cafe="\033[1;33m"
fiuscha="\033[0;35m"
blue="\033[34m"
orange="\033[38;5;122m"
# |
RED="$(printf '\033[31m')"
GREEN="$(printf '\033[32m')"
ORANGE="$(printf '\033[33m')"
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"
CYAN="$(printf '\033[36m')"
WHITE="$(printf '\033[37m')"
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"
GREENBG="$(printf '\033[42m')"
ORANGEBG="$(printf '\033[43m')"
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"
CYANBG="$(printf '\033[46m')"
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
# |
Banner(){
  echo "$BLUE
   ██████   █████                  ████
  ░░██████ ░░███                  ░░███
   ░███░███ ░███   ██████   █████  ░███   ██████
   ░███░░███░███  ███░░███ ███░░   ░███  ███░░███
   ░███ ░░██████ ░███████ ░░█████  ░███ ░███████
   ░███  ░░█████ ░███░░░   ░░░░███ ░███ ░███░░░
   █████  ░░█████░░██████  ██████  █████░░██████$RED
  ░░░░░░    ░░░░░  ░░░░░░  ░░░░░░  ░░░░░  ░░░░░░░
  ░     _   _            _  ___                 ░
  ░    | | | | __ _  ___| |/ (_)_ __   __ _     ░
  ░    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    ░
  ░    |  _  | (_| | (__| . \| | | | | (_| |    ░
  ░    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    ░
  ░                                   |___/     ░
  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
  ▒         ▀▀█▀▀ █▀▀█ █▀▀█ █   █▀▀             ▒
  ▒           █   █  █ █  █ █   ▀▀█             ▒
  ▒           ▀   ▀▀▀▀ ▀▀▀▀ ▀▀▀ ▀▀▀$ORANGE v0.0.0.1    ▒
  ▒ https://www.github.com/Anlominus/CoreMan    ▒
  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
  "
}
logo="$(Banner)"

# checking for system home dir
if [ -d $HOME ]; then
  home=$HOME
else
  home="~/"
fi

# checking for system bin dir
if [ -d /data/data/com.termux/files/usr/bin ]; then
  bin="/data/data/com.termux/files/usr/bin"
elif [ -d /usr/local/bin ]; then
  bin="/usr/local/bin"
elif [ -d /bin ]; then
  bin="/bin"
elif [ -d /sbin ]; then
  bin="/sbin"
fi

# checking for configuration dir
if [ -d /data/data/com.termux/files/usr/etc ]; then
  conf_dir="/data/data/com.termux/files/usr/etc"
elif [ -d /etc ]; then
  conf_dir="/etc"
fi

# configuration files
if [ -d $conf_dir/CoreMan ]; then
  if [ -e $conf_dir/CoreMan/data/tools.dat ]; then
    tools_data="$conf_dir/CoreMan/data/tools.dat"
  fi
  if [ -e $conf_dir/CoreMan/data/category.dat ]; then
    category_data="$conf_dir/CoreMan/data/category.dat"
  fi
else
  if [ -e data/tools.dat ]; then
    tools_data="data/tools.dat"
  fi
  if [ -e data/category.dat ]; then
    category_data="data/category.dat"
  fi
fi

# checking for system root access
if [ `command -v sudo` ]; then
  sudo="sudo"
else
  sudo=""
fi

# checking for system package manager
if [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
elif [ `command -v brew` ]; then
  pac="brew"
  system="mac"
  sudo=""
elif [ `command -v apt` ]; then
  pac="apt"
  system="linux"
elif [ `command -v apt-get` ]; then
  pac="apt-get"
  system="linux"
elif [ `command -v apk` ]; then
  pac="apk"
  system="linux"
elif [ `command -v yum` ]; then
  pac="yum"
  system="fedora"
fi

# setup process
clear
echo "$logo"
echo "${green} Installing .... ${nc}"
sleep 1
echo "${yellow} Running setup .... ${nc}"
sleep 1

# installing dependency
for each_pac in "brew" "wget" "curl" "git"; do
  if [ ! `command -v $each_pac` ]; then
    if [ $sudo ]; then
      $sudo $pac install $each_pac
    else
      $pac install $each_pac 
    fi
  fi
done

# removing old one
if [ -e $bin/CoreMan ]; then
  if [ -d $conf_dir/CoreMan ]; then
    if [ $sudo ]; then
      $sudo rm -rf $bin/CoreMan
      $sudo rm -rf $conf_dir/CoreMan
    else
      rm -rf $bin/CoreMan
      rm -rf $conf_dir/CoreMan
    fi
  fi
fi

# install CoreMan
if [ $0 = "install" -o $0 = "./install" ]; then
  if [ -e CoreMan ]; then
    if [ $sudo ]; then
      $sudo mv -v CoreMan $bin
      $sudo chmod +x $bin/CoreMan
    else
      mv -v CoreMan $bin
      chmod +x $bin/CoreMan
    fi
  fi
  cd ..
  if [ -d CoreMan ]; then
    if [ $sudo ]; then
    $sudo mv -v CoreMan $conf_dir
    else
      mv -v CoreMan $conf_dir
    fi
  fi
else
  if [ -e CoreMan/CoreMan ]; then
    if [ $sudo ]; then
      $sudo mv -v CoreMan/CoreMan $bin
      $sudo chmod +x $bin/CoreMan
    else
      mv -v CoreMan/CoreMan $bin
      chmod +x $bin/CoreMan
    fi
  fi
  if [ -d CoreMan ]; then
    if [ $sudo ]; then
    $sudo mv -v CoreMan $conf_dir
    else
      mv -v CoreMan $conf_dir
    fi
  fi
fi

# check CoreMan is installed or not
if [ -e $bin/CoreMan ]; then
  if [ -d $conf_dir/CoreMan ]; then
    clear
    echo "$logo"
    echo " ${purple}CoreMan ${green}installed successfully !!"
    echo " ${green}type ${nc}'CoreMan -h'${green} for more.${nc}"
  else
    clear
    echo "$logo"
    echo " ${red}Sorry ${cyan}: CoreMan ${red}is not installed !!"
    echo " ${green}Please try again${nc}"
  fi
fi
