#!/bin/sh
# Name : AnyTool
# Source: github.com/Anlominus/HacKing/AnyTool/AnyTool
# Date : May 2022

# Define Colors Variables
HacKingProColors(){
##############################################################################
# COLORS AND BACKGROUNDS
##############################################################################
Color_Off='\033[0m' # Text Reset

# Regular Colors
Black='\033[0;30m'  # Black
Red='\033[0;31m'    # Red
Green='\033[0;32m'  # Green
Yellow='\033[0;33m' # Yellow
Blue='\033[0;34m'   # Blue
Purple='\033[0;35m' # Purple
Cyan='\033[0;36m'   # Cyan
White='\033[0;97m'  # White

# Additional colors
LGrey='\033[0;37m'   # Ligth Gray
DGrey='\033[0;90m'   # Dark Gray
LRed='\033[0;91m'    # Ligth Red
LGreen='\033[0;92m'  # Ligth Green
LYellow='\033[0;93m' # Ligth Yellow
LBlue='\033[0;94m'   # Ligth Blue
LPurple='\033[0;95m' # Light Purple
LCyan='\033[0;96m'   # Ligth Cyan


# Bold
BBlack='\033[1;30m'  # Black
BRed='\033[1;31m'    # Red
BGreen='\033[1;32m'  # Green
BYellow='\033[1;33m' # Yellow
BBlue='\033[1;34m'   # Blue
BPurple='\033[1;35m' # Purple
BCyan='\033[1;36m'   # Cyan
BWhite='\033[1;37m'  # White

# Underline
UBlack='\033[4;30m'  # Black
URed='\033[4;31m'    # Red
UGreen='\033[4;32m'  # Green
UYellow='\033[4;33m' # Yellow
UBlue='\033[4;34m'   # Blue
UPurple='\033[4;35m' # Purple
UCyan='\033[4;36m'   # Cyan
UWhite='\033[4;37m'  # White

# Background
On_Black='\033[40m'  # Black
On_Red='\033[41m'    # Red
On_Green='\033[42m'  # Green
On_Yellow='\033[43m' # Yellow
On_Blue='\033[44m'   # Blue
On_Purple='\033[45m' # Purple
On_Cyan='\033[46m'   # Cyan
On_White='\033[47m'  # White
}
HacKingProColors
# HacKingPro Design
HacKingPro=$(echo "${BRed}Hac${BYellow}King${BBlue}Pro")
Anlominus=$(echo "${BGreen}An${DGrey}Lo${BRed}Minus")
MyVersion=$(echo "${DGrey}V0.0.0.${BWhite}15")
HacKingProDavid=$(echo "\n\t  ${BRed}[${BCyan}✡${BRed}] ${HacKingPro} ${BRed}[${BCyan}✡${BRed}]\n\t\t ${BGreen}")
HacKingProExit=$(echo "\n ${BRed}[${BCyan}✡${BRed}] ${BCyan}Exit ${HacKingPro} ${BRed}[${BCyan}✡${BRed}]\n\t\t ${BGreen}")
Press_ENTER=$(echo "\n\n${BYellow}                🔶    Press ENTER    🔶     ${BGreen}\n\n")
Press_Enter_To_START=$(echo "\n\n${BYellow}                🔶    Press Enter To START    🔶     ${BGreen}\n\n")
InvalidOption=$(echo "\n\t\t ${BGreen}»»» ${HacKingPro} ${LRed}Invalid Option ${BRed}¯\_(ツ)_/¯ \n")
#|

# |
nc="\033[00m"
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[32m"
yellow="\033[33m"
purple="\033[0;35m"
cyan="\033[1;36m"
cafe="\033[1;33m"
fiuscha="\033[0;35m"
blue="\033[34m"
orange="\033[38;5;122m"
# |
RED="$(printf '\033[31m')"
GREEN="$(printf '\033[32m')"
ORANGE="$(printf '\033[33m')"
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"
CYAN="$(printf '\033[36m')"
WHITE="$(printf '\033[37m')"
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"
GREENBG="$(printf '\033[42m')"
ORANGEBG="$(printf '\033[43m')"
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"
CYANBG="$(printf '\033[46m')"
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
# |
# Banner(){
#   echo "$BLUE
#    ██████   █████                  ████
#   ░░██████ ░░███                  ░░███
#    ░███░███ ░███   ██████   █████  ░███   ██████
#    ░███░░███░███  ███░░███ ███░░   ░███  ███░░███
#    ░███ ░░██████ ░███████ ░░█████  ░███ ░███████
#    ░███  ░░█████ ░███░░░   ░░░░███ ░███ ░███░░░
#    █████  ░░█████░░██████  ██████  █████░░██████$RED
#   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
#   ▒         ▀▀█▀▀ █▀▀█ █▀▀█ █   █▀▀             ▒
#   ▒           █   █  █ █  █ █   ▀▀█             ▒
#   ▒           ▀   ▀▀▀▀ ▀▀▀▀ ▀▀▀ ▀▀▀$ORANGE v12.0.6.4   ▒
#   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
#   "
# }
# logo="$(Banner)"
# |
MainMenu(){
  echo "
    ${DGrey}┌──${BRed}[${BYellow} AnyTool ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 01 ${BRed}]${BGreen}── ${BRed}[${LGreen} Anonymity ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 02 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Backdoor ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 03 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Enumeration  ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 04 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Exploit ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 05 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Generator ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 06 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Information ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 07 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Password ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 08 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Phishing ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 09 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Remote Access Trojan ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 10 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Reconnaissance ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 11 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Spam ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 12 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Core Package  ${BRed}]
    ${DGrey}|
    ${DGrey}|──${BRed}[${LGreen} 13 ${BRed}]${BGreen}── ${BRed}[${LGreen} Any Exploit ${BRed}]
    ${DGrey}|
    ${DGrey}└──${BRed}[${DGrey} X ${BRed}] Exit / Quit / Close"
    # ${DGrey}|──${BRed}[${DGrey} About ${BRed}]${BGreen}──╼ ${BRed}[${DGrey} Information About The ${HacKingPro} ${BRed}]
    # ${DGrey}|
    # ${BGreen}┌──${BRed}[${BCyan} Arsenal ${BRed}]${BGreen}──╼ ${BRed}[${BCyan} Cheat Sheets ${BRed}]${BGreen}──╼ ${BRed}[${BGreen} Command ${BRed}]${BGreen}──╼ ${BRed}[${LGreen} $ArsenalCommand ${BRed}]
    # ${BGreen}|

}
main_Menu="$(MainMenu)"
# |
PromptFun(){
  promptfunc=$(echo "
  ${BGreen}  ┌──${BRed}[${DGrey} ~$(pwd) ${BRed}]
  ${BGreen}  |
  ${BGreen}  └──${BRed}[${BYellow} $Anlominus ${BRed}]${BGreen}──╼ ${BRed}[${BGreen} ${HacKingPro} ${BRed}]${BGreen}──╼ ${BRed}[${BGreen} AnyTool ${BRed}]${BGreen}──╼ ${BGreen}   ")

  echo "$promptfunc"
}
prompt="$(PromptFun)"
# |
# this is the main function
  while true; do
    # tools=`grep -n '.' $tools_data | wc -l`
    # category=`grep -n '.' $category_data | wc -l`
    clear
    # echo "$logo"
    echo "$main_Menu"
    read -p "$prompt" cmd
    case ${cmd} in
      1)
      cd Anonymity
      sh Anonymity start
      cd ..
      ;;
      2)
      cd AnyBackdoor
      sh AnyBackdoor start
      cd ..
      ;;
      3)
      cd AnyEnum
      sh AnyEnum start
      cd ..
      ;;
      4)
      cd AnyExploit
      sh AnyExploit start
      cd ..
      ;;
      5)
      cd AnyGen
      sh AnyGen start
      cd ..
      ;;
      6)
      cd AnyInfo
      sh AnyInfo start
      cd ..
      ;;
      7)
      cd AnyPass
      sh AnyPass start
      cd ..
      ;;
      8)
      cd AnyPhishing
      sh AnyPhishing start
      cd ..
      ;;
      9)
      cd AnyRat
      sh AnyRat start
      cd ..
      ;;
      10)
      cd AnyRecon
      sh AnyRecon start
      cd ..
      ;;
      11)
      cd AnySpam
      sh AnySpam start
      cd ..
      ;;
      12)
      cd CoreMan
      sh CoreMan start
      cd ..
      ;;
      x|exit|Exit)
        echo "${green}Exiting ....${nc}"
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!${nc}"
        sleep 1
      ;;

    esac

  done
