#!/bin/sh
# Name : AnyTool
# Source: github.com/Anlominus/HacKing/AnyTool/AnyTool
# Date : May 2022
# |
nc="\033[00m"
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[32m"
yellow="\033[33m"
purple="\033[0;35m"
cyan="\033[1;36m"
cafe="\033[1;33m"
fiuscha="\033[0;35m"
blue="\033[34m"
orange="\033[38;5;122m"
# |
RED="$(printf '\033[31m')"
GREEN="$(printf '\033[32m')"
ORANGE="$(printf '\033[33m')"
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"
CYAN="$(printf '\033[36m')"
WHITE="$(printf '\033[37m')"
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"
GREENBG="$(printf '\033[42m')"
ORANGEBG="$(printf '\033[43m')"
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"
CYANBG="$(printf '\033[46m')"
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
# |
Banner(){
  echo "$BLUE
   ██████   █████                  ████
  ░░██████ ░░███                  ░░███
   ░███░███ ░███   ██████   █████  ░███   ██████
   ░███░░███░███  ███░░███ ███░░   ░███  ███░░███
   ░███ ░░██████ ░███████ ░░█████  ░███ ░███████
   ░███  ░░█████ ░███░░░   ░░░░███ ░███ ░███░░░
   █████  ░░█████░░██████  ██████  █████░░██████$RED
  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
  ▒         ▀▀█▀▀ █▀▀█ █▀▀█ █   █▀▀             ▒
  ▒           █   █  █ █  █ █   ▀▀█             ▒
  ▒           ▀   ▀▀▀▀ ▀▀▀▀ ▀▀▀ ▀▀▀$ORANGE v12.0.6.4   ▒
  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
  "
}
logo="$(Banner)"
# |
MainMenu(){
  echo "${cyan}     [1] ${green} Anonymity"
  echo "${cyan}     [2] ${green} AnyBackdoor"
  echo "${cyan}     [3] ${green} AnyEnum"
  echo "${cyan}     [4] ${green} AnyExploit"
  echo "${cyan}     [5] ${green} AnyGen"
  echo "${cyan}     [6] ${green} AnyInfo"
  echo "${cyan}     [7] ${green} AnyPass"
  echo "${cyan}     [8] ${green} AnyPhishing"
  echo "${cyan}     [9] ${green} AnyRat"
  echo "${cyan}     [10] ${green} AnyRecon"
  echo "${cyan}     [11] ${green} AnySpam"
  echo "${cyan}     [12] ${green} CoreMan"
  echo "${cyan}     [x] ${green} Exit"
}
main_Menu="$(MainMenu)"
# |
PromptFun(){
  promptfunc=$(echo "
  ${orange}  ┌──[${blue}Anlominus${purple}👽${red}AnyTool${cyan}$~${orange}]${cyan}
  ${orange}  └──╼${green} ")
  echo "$promptfunc"
}
prompt="$(PromptFun)"
# |
# this is the main function
  while true; do
    # tools=`grep -n '.' $tools_data | wc -l`
    # category=`grep -n '.' $category_data | wc -l`
    clear
    echo "$logo"
    echo "$main_Menu"
    read -p "$prompt" cmd
    case ${cmd} in
      1)
      cd Anonymity
      sh Anonymity start
      cd ..
      ;;
      2)
      cd AnyBackdoor
      sh AnyBackdoor start
      cd ..
      ;;
      3)
      cd AnyEnum
      sh AnyEnum start
      cd ..
      ;;
      4)
      cd AnyExploit
      sh AnyExploit start
      cd ..
      ;;
      5)
      cd AnyGen
      sh AnyGen start
      cd ..
      ;;
      6)
      cd AnyInfo
      sh AnyInfo start
      cd ..
      ;;
      7)
      cd AnyPass
      sh AnyPass start
      cd ..
      ;;
      8)
      cd AnyPhishing
      sh AnyPhishing start
      cd ..
      ;;
      9)
      cd AnyRat
      sh AnyRat start
      cd ..
      ;;
      10)
      cd AnyRecon
      sh AnyRecon start
      cd ..
      ;;
      11)
      cd AnySpam
      sh AnySpam start
      cd ..
      ;;
      12)
      cd CoreMan
      sh CoreMan start
      cd ..
      ;;
      x|exit|Exit)
        echo "${green}Exiting ....${nc}"
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!${nc}"
        sleep 1
      ;;

    esac

  done
