language: python
python:
    - 2.7
    - 3.6
    - 3.9

before_install:
    - pip install pytest pygments markdown coveralls
    - pip install -e .

before_script:
  - "echo 'starting'"
  - "echo $PYTHONPATH"

script:
    coverage run --include="mdv/markdownviewer.py"  setup.py test
    
after_success:
    coveralls

