#!/bin/bash
# version 2.0
# src: https://github.com/Genixcyber/Hacker-X
clear

Installig(){
  #!/bin/bash
#installation

clear

gem install lolcat
apt install toilet -y
echo ""
echo ""
echo "                               VISIT MY WEBSITE 🔔 " |lolcat
xdg-open https://Technocyber.tk
echo ""

echo -e "\e[101m Press Enter \e[0m"
read a1

sleep 1
clear

echo "Loading..." |lolcat
sleep 1
clear

echo "Loading..." |lolcat
sleep 1
clear

echo "Loading..." |lolcat
sleep 1
clear

printf "\e[0m\n"
printf "\e[0m\e[93m _________ _______  _______           _        _______  _______           ______   _______  _______ \e[0m\n"
printf "\e[0m\e[93m \__   __/(  ____ \(  ____ \|\     /|( (    /|(  ___  )(  ____ \|\     /|(  ___ \ (  ____ \(  ____ )\e[0m\n"
printf "\e[0m\e[93m    ) (   | (    \/| (    \/| )   ( ||  \  ( || (   ) || (    \/( \   / )| (   ) )| (    \/| (    )|\e[0m\n"
printf "\e[0m\e[93m    | |   | (__    | |      | (___) ||   \ | || |   | || |       \ (_) / | (__/ / | (__    | (____)|\e[0m\n"
printf "\e[0m\e[93m    | |   |  __)   | |      |  ___  || (\ \) || |   | || |        \   /  |  __ (  |  __)   |     __)\e[0m\n"
printf "\e[0m\e[93m    | |   | (      | |      | (   ) || | \   || |   | || |         ) (   | (  \ \ | (      | (\ (\e[0m\n"
printf "\e[0m\e[93m    | |   | (____/\| (____/\| )   ( || )  \  || (___) || (____/\   | |   | )___) )| (____/\| ) \ \__\e[0m\n"
printf "\e[0m\e[93m    )_(   (_______/(_______/|/     \||/    )_)(_______)(_______/   \_/   |/ \___/ (_______/|/   \__/\e[0m\n"
printf "\e[0m\n"
printf " \e[0m\e                                 ======[ INSTALLING DEPENDENCIES ]======\e[0m\n"
printf "\e[0m\n"

trap ctrl_c INT
ctrl_c() {
clear
echo  "Detected, Trying To Exit  ... "
echo ""
sleep 1
echo ""
echo "TECHNOCYBER" |lolcat
sleep 1
exit
}

apt update
apt upgrade -y
pkg install ruby -y
pkg install figlet
pkg install wget
pkg install git -y
pkg install python -y
pkg install python2 -y
pkg install git -y
pip install lolcat
apt install git php openssh curl -y
pkg install python2 -y
pip install --upgrade pip
pkg install nano php -y
pip2 install mechanize
pip2 install --upgrade pip
clear

echo ""
echo "Coded By TECHNOCYBER" |lolcat
echo "________________________" |lolcat
sleep 10
echo ""
}

echo ""
echo -e "VISIT MY WEBSITE"
echo ""

echo -e "\e[101m Press Enter \e[0m"
read a1

echo "Loading..." |lolcat
sleep 2
clear

printf "\e[0m\n"
printf "\e[0m\e[93m  _  _   __    ___  __ _  ____  ____      _  _ \e[0m\n"
printf "\e[0m\e[93m / )( \ / _\  / __)(  / )(  __)(  _ \ ___( \/ )\e[0m\n"
printf "\e[0m\e[96m ) __ (/    \( (__  )  (  ) _)  )   /(___))  ( \e[0m\n"
printf "\e[0m\e[96m \_)(_/\_/\_/ \___)(__\_)(____)(__\_)    (_/\_)\e[0m\n"
printf "\e[0m\n"
echo "-------------------------------------------------------" |lolcat
echo   "Created BY  : TECHNO - CYBER - $white" |lolcat
echo   "Contact  : Instagram.com/Technocyber.sh.com $white" |lolcat
echo "-------------------------------------------------------" |lolcat
###################################################
#
###################################################
user_interrupt(){
        printf "\e[0m\n"
        printf "\e[0m\e[1;36m\t CTRL + C Pressed !!\n"
        sleep 2
        printf "\e[0m\n"
        printf " \e[0m\e[1;42m Thanks for Using This Tool !!\e[0m  \e[1;44m Visit https://github.com/Technocyber for more\e[0m\n"
        printf "\e[0m\n"
        printf " \e[1;37m                             [ YOURS IR170 ]\e[0m\n"
        printf "\e[0m\n"
        exit 1
}



lagi=01
while [ $lagi -lt 15 ];
do
printf "\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m01\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X            \e[0m\e[1;31m[\e[0m\e[1;77m31\e[0m\e[1;31m]\e[0m\e[0m\e[96m Fb-Bruter             \e[1;31m[\e[0m\e[1;77m61\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m02\e[0m\e[1;31m]\e[0m\e[0m\e[96m T2-fisher         \e[0m\e[1;31m[\e[0m\e[1;77m32\e[0m\e[1;31m]\e[0m\e[0m\e[96m Ipdrone               \e[1;31m[\e[0m\e[1;77m62\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m03\e[0m\e[1;31m]\e[0m\e[0m\e[96m Metasploit        \e[0m\e[1;31m[\e[0m\e[1;77m33\e[0m\e[1;31m]\e[0m\e[0m\e[96m Instagram-Bruteforce  \e[1;31m[\e[0m\e[1;77m63\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m04\e[0m\e[1;31m]\e[0m\e[0m\e[96m Nexphisher        \e[0m\e[1;31m[\e[0m\e[1;77m34\e[0m\e[1;31m]\e[0m\e[0m\e[96m Red_HAWK              \e[1;31m[\e[0m\e[1;77m64\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m05\e[0m\e[1;31m]\e[0m\e[0m\e[96m Ip-Tracer         \e[0m\e[1;31m[\e[0m\e[1;77m35\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tech-COCHI            \e[1;31m[\e[0m\e[1;77m65\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m06\e[0m\e[1;31m]\e[0m\e[0m\e[96m Phoneinfoga       \e[0m\e[1;31m[\e[0m\e[1;77m36\e[0m\e[1;31m]\e[0m\e[0m\e[96m Z-phisher             \e[1;31m[\e[0m\e[1;77m66\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m07\e[0m\e[1;31m]\e[0m\e[0m\e[96m Infect            \e[0m\e[1;31m[\e[0m\e[1;77m37\e[0m\e[1;31m]\e[0m\e[0m\e[96m Facebook-Bruteforce   \e[1;31m[\e[0m\e[1;77m67\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m08\e[0m\e[1;31m]\e[0m\e[0m\e[96m SQL-Map           \e[0m\e[1;31m[\e[0m\e[1;77m38\e[0m\e[1;31m]\e[0m\e[0m\e[96m WEEMAN                \e[1;31m[\e[0m\e[1;77m68\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m09\e[0m\e[1;31m]\e[0m\e[0m\e[96m Mr-Phish          \e[0m\e[1;31m[\e[0m\e[1;77m39\e[0m\e[1;31m]\e[0m\e[0m\e[96m Termux-Basic-Package  \e[1;31m[\e[0m\e[1;77m69\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m10\e[0m\e[1;31m]\e[0m\e[0m\e[96m NMAP              \e[0m\e[1;31m[\e[0m\e[1;77m40\e[0m\e[1;31m]\e[0m\e[0m\e[96m Shark                 \e[1;31m[\e[0m\e[1;77m70\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m11\e[0m\e[1;31m]\e[0m\e[0m\e[96m T-BOMB            \e[0m\e[1;31m[\e[0m\e[1;77m41\e[0m\e[1;31m]\e[0m\e[0m\e[96m Email-Bomber          \e[1;31m[\e[0m\e[1;77m71\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m12\e[0m\e[1;31m]\e[0m\e[0m\e[96m Termuxarch        \e[0m\e[1;31m[\e[0m\e[1;77m42\e[0m\e[1;31m]\e[0m\e[0m\e[96m The_inspector         \e[1;31m[\e[0m\e[1;77m72\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m13\e[0m\e[1;31m]\e[0m\e[0m\e[96m Lazybee           \e[0m\e[1;31m[\e[0m\e[1;77m43\e[0m\e[1;31m]\e[0m\e[0m\e[96m Little_Brother        \e[1;31m[\e[0m\e[1;77m73\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m14\e[0m\e[1;31m]\e[0m\e[0m\e[96m Lucifer           \e[0m\e[1;31m[\e[0m\e[1;77m44\e[0m\e[1;31m]\e[0m\e[0m\e[96m Cred-Map              \e[1;31m[\e[0m\e[1;77m74\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m15\e[0m\e[1;31m]\e[0m\e[0m\e[96m Grabcam           \e[0m\e[1;31m[\e[0m\e[1;77m45\e[0m\e[1;31m]\e[0m\e[0m\e[96m Ubuntu                \e[1;31m[\e[0m\e[1;77m75\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m16\e[0m\e[1;31m]\e[0m\e[0m\e[96m T_Load            \e[0m\e[1;31m[\e[0m\e[1;77m46\e[0m\e[1;31m]\e[0m\e[0m\e[96m TLock                 \e[1;31m[\e[0m\e[1;77m76\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m17\e[0m\e[1;31m]\e[0m\e[0m\e[96m Nikto             \e[0m\e[1;31m[\e[0m\e[1;77m47\e[0m\e[1;31m]\e[0m\e[0m\e[96m Odi.g                 \e[1;31m[\e[0m\e[1;77m77\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m18\e[0m\e[1;31m]\e[0m\e[0m\e[96m Seeker            \e[0m\e[1;31m[\e[0m\e[1;77m48\e[0m\e[1;31m]\e[0m\e[0m\e[96m Gemail_Hack           \e[1;31m[\e[0m\e[1;77m78\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m19\e[0m\e[1;31m]\e[0m\e[0m\e[96m Hunner            \e[0m\e[1;31m[\e[0m\e[1;77m49\e[0m\e[1;31m]\e[0m\e[0m\e[96m Black_Eye             \e[1;31m[\e[0m\e[1;77m79\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m20\e[0m\e[1;31m]\e[0m\e[0m\e[96m Key-mux           \e[0m\e[1;31m[\e[0m\e[1;77m50\e[0m\e[1;31m]\e[0m\e[0m\e[96m Malicious             \e[1;31m[\e[0m\e[1;77m80\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m21\e[0m\e[1;31m]\e[0m\e[0m\e[96m Fsociety-Toolkit  \e[0m\e[1;31m[\e[0m\e[1;77m51\e[0m\e[1;31m]\e[0m\e[0m\e[96m Black_Box             \e[1;31m[\e[0m\e[1;77m81\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m22\e[0m\e[1;31m]\e[0m\e[0m\e[96m EasY_Hack         \e[0m\e[1;31m[\e[0m\e[1;77m52\e[0m\e[1;31m]\e[0m\e[0m\e[96m Bash Fingerprinting   \e[1;31m[\e[0m\e[1;77m82\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m23\e[0m\e[1;31m]\e[0m\e[0m\e[96m Anon-Sms          \e[0m\e[1;31m[\e[0m\e[1;77m53\e[0m\e[1;31m]\e[0m\e[0m\e[96m Hidden_Eye            \e[1;31m[\e[0m\e[1;77m83\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m24\e[0m\e[1;31m]\e[0m\e[0m\e[96m Dragonbrute_fb    \e[0m\e[1;31m[\e[0m\e[1;77m54\e[0m\e[1;31m]\e[0m\e[0m\e[96m Social_Fish           \e[1;31m[\e[0m\e[1;77m84\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m25\e[0m\e[1;31m]\e[0m\e[0m\e[96m websploit         \e[0m\e[1;31m[\e[0m\e[1;77m55\e[0m\e[1;31m]\e[0m\e[0m\e[96m Dos                   \e[1;31m[\e[0m\e[1;77m85\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m26\e[0m\e[1;31m]\e[0m\e[0m\e[96m GoldenEyeDDos     \e[0m\e[1;31m[\e[0m\e[1;77m56\e[0m\e[1;31m]\e[0m\e[0m\e[96m                       \e[1;31m[\e[0m\e[1;77m86\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m27\e[0m\e[1;31m]\e[0m\e[0m\e[96m wifite            \e[0m\e[1;31m[\e[0m\e[1;77m57\e[0m\e[1;31m]\e[0m\e[0m\e[96m Haxrat                \e[1;31m[\e[0m\e[1;77m87\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m28\e[0m\e[1;31m]\e[0m\e[0m\e[96m dedsploit         \e[0m\e[1;31m[\e[0m\e[1;77m58\e[0m\e[1;31m]\e[0m\e[0m\e[96m Spotify               \e[1;31m[\e[0m\e[1;77m88\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m29\e[0m\e[1;31m]\e[0m\e[0m\e[96m WPscan            \e[0m\e[1;31m[\e[0m\e[1;77m59\e[0m\e[1;31m]\e[0m\e[0m\e[96m Reddit                \e[1;31m[\e[0m\e[1;77m89\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf " \e[1;31m[\e[0m\e[1;77m30\e[0m\e[1;31m]\e[0m\e[0m\e[96m CyberScan         \e[0m\e[1;31m[\e[0m\e[1;77m60\e[0m\e[1;31m]\e[0m\e[0m\e[96m Adobe                 \e[1;31m[\e[0m\e[1;77m90\e[0m\e[1;31m]\e[0m\e[0m\e[96m Tool-X\e[0m\n"
printf "\e[0m\n"
echo  "╭─TECHNOCYBER" |lolcat
read -p "╰──►" pil;


#Tool-X


case $pil in
1) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/Rajkumrdusad/Tool-X
cd Tool-X
sh install.aex


;;


#T2-FISHER


2) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/2Timeowl/T2-fisher.git
cd T2-fisher
chmod +x *
bash setup
ls
bash T2-fisher


;;


#METASPLOIT


3) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/Punker-Bhai/blacky-console
cd blacky-console
bash console.sh


;;


#NEXPHISHER



4) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone git://github.com/htr-tech/nexphisher.git
cd nexphisher
bash setup
bash nexphisher


;;


#IP-TRACER


5) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/Punker-Bhai/tracer-ip.git
cd tracer-ip
bash ip.sh

;;


#PHONEINFOGA


6) clear
toilet -f standard " TECHNOCYBER " -F gay
curl -LO https://raw.githubusercontent.com/Technocyber/T2-Osint/master/T2-Osint.sh
bash T2-Osint.sh


;;


#INFECT


7) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/noob-hackers/infect
cd $HOME
ls
cd infect
ls
bash infect.sh


;;


#SQLMAP


8) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/sqlmapproject/sqlmap
cd sqlmap
chmod +x sqlmap.py
python2 sqlmap.py

;;


#MR.PHISH


9) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/noob-hackers/mrphish
cd $HOME
cd mrphish
bash setup
bash mrphish

;;


#NMAP


10) clear
toilet -f standard " TECHNOCYBER " -F gay
pkg install nmap

;;


#TBOMB


11) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/TheSpeedX/TBomb.git
cd TBomb
chmod +x TBomb.sh
./TBomb.sh


;;


#TERMUXARCH


12) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/sdrausty/TermuxArch
bash TermuxArch/setupTermuxArch.sh


;;


#LAZYBEE


13) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/noob-hackers/lazybee
cd $HOME
ls
cd lazybee
ls
python2 lazybee.py

;;


#LUCIFER


14) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/rixon-cochi/Lucifer.git
cd Lucifer
chmod +x *
bash setup.sh
bash instacracker.sh


;;


#SAYCHEESE


15) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/noob-hackers/grabcam
cd $HOME
ls
cd grabcam
ls
bash grabcam.sh

;;

#T-LOAD


16)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/noob-hackers/T-LOAD
cd $HOME
cd T-LOAD
bash t-load.sh

;;

#NIKTO


17)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/sullo/nikto
cd nikto/program

;;



#SEEKER


18) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/thewhiteh4t/seeker.git
cd seeker/
pkg update
pkg install python php
pip3 install requests


;;


#HUNNER


19) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://GitHub.com/b3-v3r/hunner
cd hunner
python2 hunner.py

;;


#KEY_MUX


20) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/Punker-Bhai/key-mux
cd key-mux
bash mux.sh

;;


#FSOCIETY_TOOLKIT


21) clear
toilet -f standard " TECHNOCYBER " -F gay
https://github.com/Manisso/fsociety.git
cd fsociety
chmod +x install.sh

;;


#EASY_HACK


22) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/sabri-zaki/EasY_HaCk
cd EasY_HaCk/
chmod +x install.sh
Type EasY-HaCk



;;


#ANON-SMS


23) clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/noob-hackers/spamx
cd $HOME
ls
cd spamx
ls
bash setup.sh
bash spamx.sh

;;


#BRUTEFORCE_FB


24)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/Oseid/FaceBoom.git
cd FaceBoom/
pip install requests
pip install mechanize



;;


#WEBSPLOIT


25)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/websploit/websploit.git
cd websploit
python setup.py install

;;

#GOLDENEYE_DDOS


26)clear
toilet -f standard " TECHNOCYBER " -F gay
https://github.com/jseidl/GoldenEye.git
cd GoldenEye
python3 goldeneye.py

;;

#WIFITE


27)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/derv82/wifite2.git
cd wifite2
sudo ./Wifite.py


;;

#
DEDSPLOIT

28)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone https://github.com/R3K1NG/dedsploit
cd dedsploit
./installer

;;

#WPSCAN


29)clear
toilet -f standard " TECHNOCYBER " -F gay
gem install wpscan

;;

#WPSCAN


30)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone


;;

#CYBERSCAN


31)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#FB-BRUTER


32)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#IPDRONE


33)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#INSTAGRAM_BRUTEFORCE


34)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#RED_HAWK


35)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#TECH_COCHI


36)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#Z-PHISHER


37)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#FACEBOOK_BRUTEFORCE


38)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#WEEMAN


39)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#TERMUX_BASIC_PACKAGE


40)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#SHARK


41)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#EMAIL_BOMBER


42)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#THE_INSPECTOR


43)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#LITTLE_BROTHER


44)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#CRED_MAP


45)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#UBUNTU


46)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#TLOCK


47)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#ODI.G


48)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#GEMAIL_HACK


49)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#HIDDEN_EYE


50)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#BLACK_EYE


51)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#SOCIALFISH


52)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#


53)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#MALICIOUS


54)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#BLACKBOX


55)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;

#BASH_FINGERPRINT


56)clear
toilet -f standard " TECHNOCYBER " -F gay
git clone

;;


00) echo "Coded By: TECHNOCYBER" |lolcat
exit
;;

*) echo "Invalid Option Chosen" |lolcat
esac
done
done

=================="
