name: Publish Book

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Genearte Index Page
      run: cat ./README.md >> ./content/_index.md

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.84.3'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        emptyCommits: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
